//
//  Mime.swift
//  MimeLibGenerator
//
//  Created by Ondrej Rafaj on 14/12/2016.
//  Copyright © 2016 manGoweb UK Ltd. All rights reserved.
//
//  Data has been extracted from an apache.org svn repository located on http://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types

import Foundation


// Warning: Do not change, following code has been automatically generated!

public class Mime {

	public static func get(fileExtension ext: String) -> MimeType? {
		switch ext {
		case "ez":
			return .ez
		case "aw":
			return .aw
		case "atom":
			return .atom
		case "atomcat":
			return .atomcat
		case "atomsvc":
			return .atomsvc
		case "ccxml":
			return .ccxml
		case "cdmia":
			return .cdmia
		case "cdmic":
			return .cdmic
		case "cdmid":
			return .cdmid
		case "cdmio":
			return .cdmio
		case "cdmiq":
			return .cdmiq
		case "cu":
			return .cu
		case "davmount":
			return .davmount
		case "dbk":
			return .dbk
		case "dssc":
			return .dssc
		case "xdssc":
			return .xdssc
		case "ecma":
			return .ecma
		case "emma":
			return .emma
		case "epub":
			return .epub
		case "exi":
			return .exi
		case "pfr":
			return .pfr
		case "gml":
			return .gml
		case "gpx":
			return .gpx
		case "gxf":
			return .gxf
		case "stk":
			return .stk
		case "ink":
			return .ink
		case "inkml":
			return .ink
		case "ipfix":
			return .ipfix
		case "jar":
			return .jar
		case "ser":
			return .ser
		case "class":
			return ._class
		case "js":
			return .js
		case "json":
			return .json
		case "jsonml":
			return .jsonml
		case "lostxml":
			return .lostxml
		case "hqx":
			return .hqx
		case "cpt":
			return .cpt
		case "mads":
			return .mads
		case "mrc":
			return .mrc
		case "mrcx":
			return .mrcx
		case "ma":
			return .ma
		case "nb":
			return .ma
		case "mb":
			return .ma
		case "mathml":
			return .mathml
		case "mbox":
			return .mbox
		case "mscml":
			return .mscml
		case "metalink":
			return .metalink
		case "meta4":
			return .meta4
		case "mets":
			return .mets
		case "mods":
			return .mods
		case "m21":
			return .m21
		case "mp21":
			return .m21
		case "mp4s":
			return .mp4s
		case "doc":
			return .doc
		case "dot":
			return .doc
		case "mxf":
			return .mxf
		case "bin":
			return .bin
		case "dms":
			return .bin
		case "lrf":
			return .bin
		case "mar":
			return .bin
		case "so":
			return .bin
		case "dist":
			return .bin
		case "distz":
			return .bin
		case "pkg":
			return .bin
		case "bpk":
			return .bin
		case "dump":
			return .bin
		case "elc":
			return .bin
		case "deploy":
			return .bin
		case "oda":
			return .oda
		case "opf":
			return .opf
		case "ogx":
			return .ogx
		case "omdoc":
			return .omdoc
		case "onetoc":
			return .onetoc
		case "onetoc2":
			return .onetoc
		case "onetmp":
			return .onetoc
		case "onepkg":
			return .onetoc
		case "oxps":
			return .oxps
		case "xer":
			return .xer
		case "pdf":
			return .pdf
		case "pgp":
			return .pgp
		case "asc":
			return .asc
		case "sig":
			return .asc
		case "prf":
			return .prf
		case "p10":
			return .p10
		case "p7m":
			return .p7m
		case "p7c":
			return .p7m
		case "p7s":
			return .p7s
		case "p8":
			return .p8
		case "ac":
			return .ac
		case "cer":
			return .cer
		case "crl":
			return .crl
		case "pkipath":
			return .pkipath
		case "pki":
			return .pki
		case "pls":
			return .pls
		case "ai":
			return .ai
		case "eps":
			return .ai
		case "ps":
			return .ai
		case "cww":
			return .cww
		case "pskcxml":
			return .pskcxml
		case "rdf":
			return .rdf
		case "rif":
			return .rif
		case "rnc":
			return .rnc
		case "rl":
			return .rl
		case "rld":
			return .rld
		case "rs":
			return .rs
		case "gbr":
			return .gbr
		case "mft":
			return .mft
		case "roa":
			return .roa
		case "rsd":
			return .rsd
		case "rss":
			return .rss
		case "rtf":
			return .rtf
		case "sbml":
			return .sbml
		case "scq":
			return .scq
		case "scs":
			return .scs
		case "spq":
			return .spq
		case "spp":
			return .spp
		case "sdp":
			return .sdp
		case "setpay":
			return .setpay
		case "setreg":
			return .setreg
		case "shf":
			return .shf
		case "smi":
			return .smi
		case "smil":
			return .smi
		case "rq":
			return .rq
		case "srx":
			return .srx
		case "gram":
			return .gram
		case "grxml":
			return .grxml
		case "sru":
			return .sru
		case "ssdl":
			return .ssdl
		case "ssml":
			return .ssml
		case "tei":
			return .tei
		case "teicorpus":
			return .tei
		case "tfi":
			return .tfi
		case "tsd":
			return .tsd
		case "plb":
			return .plb
		case "psb":
			return .psb
		case "pvb":
			return .pvb
		case "tcap":
			return .tcap
		case "pwn":
			return .pwn
		case "aso":
			return .aso
		case "imp":
			return .imp
		case "acu":
			return .acu
		case "atc":
			return .atc
		case "acutc":
			return .atc
		case "air":
			return .air
		case "fcdt":
			return .fcdt
		case "fxp":
			return .fxp
		case "fxpl":
			return .fxp
		case "xdp":
			return .xdp
		case "xfdf":
			return .xfdf
		case "ahead":
			return .ahead
		case "azf":
			return .azf
		case "azs":
			return .azs
		case "azw":
			return .azw
		case "acc":
			return .acc
		case "ami":
			return .ami
		case "apk":
			return .apk
		case "cii":
			return .cii
		case "fti":
			return .fti
		case "atx":
			return .atx
		case "mpkg":
			return .mpkg
		case "m3u8":
			return .m3u8
		case "swi":
			return .swi
		case "iota":
			return .iota
		case "aep":
			return .aep
		case "mpm":
			return .mpm
		case "bmi":
			return .bmi
		case "rep":
			return .rep
		case "cdxml":
			return .cdxml
		case "mmd":
			return .mmd
		case "cdy":
			return .cdy
		case "cla":
			return .cla
		case "rp9":
			return .rp9
		case "c4g":
			return .c4g
		case "c4d":
			return .c4g
		case "c4f":
			return .c4g
		case "c4p":
			return .c4g
		case "c4u":
			return .c4g
		case "c11amc":
			return .c11amc
		case "c11amz":
			return .c11amz
		case "csp":
			return .csp
		case "cdbcmsg":
			return .cdbcmsg
		case "cmc":
			return .cmc
		case "clkx":
			return .clkx
		case "clkk":
			return .clkk
		case "clkp":
			return .clkp
		case "clkt":
			return .clkt
		case "clkw":
			return .clkw
		case "wbs":
			return .wbs
		case "pml":
			return .pml
		case "ppd":
			return .ppd
		case "car":
			return .car
		case "pcurl":
			return .pcurl
		case "dart":
			return .dart
		case "rdz":
			return .rdz
		case "uvf":
			return .uvf
		case "uvvf":
			return .uvf
		case "uvd":
			return .uvf
		case "uvvd":
			return .uvf
		case "uvt":
			return .uvt
		case "uvvt":
			return .uvt
		case "uvx":
			return .uvx
		case "uvvx":
			return .uvx
		case "uvz":
			return .uvz
		case "uvvz":
			return .uvz
		case "fe_launch":
			return .fe_launch
		case "dna":
			return .dna
		case "mlp":
			return .mlp
		case "dpg":
			return .dpg
		case "dfac":
			return .dfac
		case "kpxx":
			return .kpxx
		case "ait":
			return .ait
		case "svc":
			return .svc
		case "geo":
			return .geo
		case "mag":
			return .mag
		case "nml":
			return .nml
		case "esf":
			return .esf
		case "msf":
			return .msf
		case "qam":
			return .qam
		case "slt":
			return .slt
		case "ssf":
			return .ssf
		case "es3":
			return .es3
		case "et3":
			return .es3
		case "ez2":
			return .ez2
		case "ez3":
			return .ez3
		case "fdf":
			return .fdf
		case "mseed":
			return .mseed
		case "seed":
			return .seed
		case "dataless":
			return .seed
		case "gph":
			return .gph
		case "ftc":
			return .ftc
		case "fm":
			return .fm
		case "frame":
			return .fm
		case "maker":
			return .fm
		case "book":
			return .fm
		case "fnc":
			return .fnc
		case "ltf":
			return .ltf
		case "fsc":
			return .fsc
		case "oas":
			return .oas
		case "oa2":
			return .oa2
		case "oa3":
			return .oa3
		case "fg5":
			return .fg5
		case "bh2":
			return .bh2
		case "ddd":
			return .ddd
		case "xdw":
			return .xdw
		case "xbd":
			return .xbd
		case "fzs":
			return .fzs
		case "txd":
			return .txd
		case "ggb":
			return .ggb
		case "ggt":
			return .ggt
		case "gex":
			return .gex
		case "gre":
			return .gex
		case "gxt":
			return .gxt
		case "g2w":
			return .g2w
		case "g3w":
			return .g3w
		case "gmx":
			return .gmx
		case "kml":
			return .kml
		case "kmz":
			return .kmz
		case "gqf":
			return .gqf
		case "gqs":
			return .gqf
		case "gac":
			return .gac
		case "ghf":
			return .ghf
		case "gim":
			return .gim
		case "grv":
			return .grv
		case "gtm":
			return .gtm
		case "tpl":
			return .tpl
		case "vcg":
			return .vcg
		case "hal":
			return .hal
		case "zmm":
			return .zmm
		case "hbci":
			return .hbci
		case "les":
			return .les
		case "hpgl":
			return .hpgl
		case "hpid":
			return .hpid
		case "hps":
			return .hps
		case "jlt":
			return .jlt
		case "pcl":
			return .pcl
		case "pclxl":
			return .pclxl
		case "sfd-hdstx":
			return .sfdHdstx
		case "mpy":
			return .mpy
		case "afp":
			return .afp
		case "listafp":
			return .afp
		case "list3820":
			return .afp
		case "irm":
			return .irm
		case "sc":
			return .sc
		case "icc":
			return .icc
		case "icm":
			return .icc
		case "igl":
			return .igl
		case "ivp":
			return .ivp
		case "ivu":
			return .ivu
		case "igm":
			return .igm
		case "xpw":
			return .xpw
		case "xpx":
			return .xpw
		case "i2g":
			return .i2g
		case "qbo":
			return .qbo
		case "qfx":
			return .qfx
		case "rcprofile":
			return .rcprofile
		case "irp":
			return .irp
		case "xpr":
			return .xpr
		case "fcs":
			return .fcs
		case "jam":
			return .jam
		case "rms":
			return .rms
		case "jisp":
			return .jisp
		case "joda":
			return .joda
		case "ktz":
			return .ktz
		case "ktr":
			return .ktz
		case "karbon":
			return .karbon
		case "chrt":
			return .chrt
		case "kfo":
			return .kfo
		case "flw":
			return .flw
		case "kon":
			return .kon
		case "kpr":
			return .kpr
		case "kpt":
			return .kpr
		case "ksp":
			return .ksp
		case "kwd":
			return .kwd
		case "kwt":
			return .kwd
		case "htke":
			return .htke
		case "kia":
			return .kia
		case "kne":
			return .kne
		case "knp":
			return .kne
		case "skp":
			return .skp
		case "skd":
			return .skp
		case "skt":
			return .skp
		case "skm":
			return .skp
		case "sse":
			return .sse
		case "lasxml":
			return .lasxml
		case "lbd":
			return .lbd
		case "lbe":
			return .lbe
		case "123":
			return ._123
		case "apr":
			return .apr
		case "pre":
			return .pre
		case "nsf":
			return .nsf
		case "org":
			return .org
		case "scm":
			return .scm
		case "lwp":
			return .lwp
		case "portpkg":
			return .portpkg
		case "mcd":
			return .mcd
		case "mc1":
			return .mc1
		case "cdkey":
			return .cdkey
		case "mwf":
			return .mwf
		case "mfm":
			return .mfm
		case "flo":
			return .flo
		case "igx":
			return .igx
		case "mif":
			return .mif
		case "daf":
			return .daf
		case "dis":
			return .dis
		case "mbk":
			return .mbk
		case "mqy":
			return .mqy
		case "msl":
			return .msl
		case "plc":
			return .plc
		case "txf":
			return .txf
		case "mpn":
			return .mpn
		case "mpc":
			return .mpc
		case "xul":
			return .xul
		case "cil":
			return .cil
		case "cab":
			return .cab
		case "xls":
			return .xls
		case "xlm":
			return .xls
		case "xla":
			return .xls
		case "xlc":
			return .xls
		case "xlt":
			return .xls
		case "xlw":
			return .xls
		case "xlam":
			return .xlam
		case "xlsb":
			return .xlsb
		case "xlsm":
			return .xlsm
		case "xltm":
			return .xltm
		case "eot":
			return .eot
		case "chm":
			return .chm
		case "ims":
			return .ims
		case "lrm":
			return .lrm
		case "thmx":
			return .thmx
		case "cat":
			return .cat
		case "stl":
			return .stl
		case "ppt":
			return .ppt
		case "pps":
			return .ppt
		case "pot":
			return .ppt
		case "ppam":
			return .ppam
		case "pptm":
			return .pptm
		case "sldm":
			return .sldm
		case "ppsm":
			return .ppsm
		case "potm":
			return .potm
		case "mpp":
			return .mpp
		case "mpt":
			return .mpp
		case "docm":
			return .docm
		case "dotm":
			return .dotm
		case "wps":
			return .wps
		case "wks":
			return .wps
		case "wcm":
			return .wps
		case "wdb":
			return .wps
		case "wpl":
			return .wpl
		case "xps":
			return .xps
		case "mseq":
			return .mseq
		case "mus":
			return .mus
		case "msty":
			return .msty
		case "taglet":
			return .taglet
		case "nlu":
			return .nlu
		case "ntf":
			return .ntf
		case "nitf":
			return .ntf
		case "nnd":
			return .nnd
		case "nns":
			return .nns
		case "nnw":
			return .nnw
		case "ngdat":
			return .ngdat
		case "n-gage":
			return .nGage
		case "rpst":
			return .rpst
		case "rpss":
			return .rpss
		case "edm":
			return .edm
		case "edx":
			return .edx
		case "ext":
			return .ext
		case "odc":
			return .odc
		case "otc":
			return .otc
		case "odb":
			return .odb
		case "odf":
			return .odf
		case "odft":
			return .odft
		case "odg":
			return .odg
		case "otg":
			return .otg
		case "odi":
			return .odi
		case "oti":
			return .oti
		case "odp":
			return .odp
		case "otp":
			return .otp
		case "ods":
			return .ods
		case "ots":
			return .ots
		case "odt":
			return .odt
		case "odm":
			return .odm
		case "ott":
			return .ott
		case "oth":
			return .oth
		case "xo":
			return .xo
		case "dd2":
			return .dd2
		case "oxt":
			return .oxt
		case "pptx":
			return .pptx
		case "sldx":
			return .sldx
		case "ppsx":
			return .ppsx
		case "potx":
			return .potx
		case "xlsx":
			return .xlsx
		case "xltx":
			return .xltx
		case "docx":
			return .docx
		case "dotx":
			return .dotx
		case "mgp":
			return .mgp
		case "dp":
			return .dp
		case "esa":
			return .esa
		case "pdb":
			return .pdb
		case "pqa":
			return .pdb
		case "oprc":
			return .pdb
		case "paw":
			return .paw
		case "str":
			return .str
		case "ei6":
			return .ei6
		case "efif":
			return .efif
		case "wg":
			return .wg
		case "plf":
			return .plf
		case "pbd":
			return .pbd
		case "box":
			return .box
		case "mgz":
			return .mgz
		case "qps":
			return .qps
		case "ptid":
			return .ptid
		case "qxd":
			return .qxd
		case "qxt":
			return .qxd
		case "qwd":
			return .qxd
		case "qwt":
			return .qxd
		case "qxl":
			return .qxd
		case "qxb":
			return .qxd
		case "bed":
			return .bed
		case "mxl":
			return .mxl
		case "musicxml":
			return .musicxml
		case "cryptonote":
			return .cryptonote
		case "cod":
			return .cod
		case "rm":
			return .rm
		case "rmvb":
			return .rmvb
		case "link66":
			return .link66
		case "st":
			return .st
		case "see":
			return .see
		case "sema":
			return .sema
		case "semd":
			return .semd
		case "semf":
			return .semf
		case "ifm":
			return .ifm
		case "itp":
			return .itp
		case "iif":
			return .iif
		case "ipk":
			return .ipk
		case "twd":
			return .twd
		case "twds":
			return .twd
		case "mmf":
			return .mmf
		case "teacher":
			return .teacher
		case "sdkm":
			return .sdkm
		case "sdkd":
			return .sdkm
		case "dxp":
			return .dxp
		case "sfs":
			return .sfs
		case "sdc":
			return .sdc
		case "sda":
			return .sda
		case "sdd":
			return .sdd
		case "smf":
			return .smf
		case "sdw":
			return .sdw
		case "vor":
			return .sdw
		case "sgl":
			return .sgl
		case "smzip":
			return .smzip
		case "sm":
			return .sm
		case "sxc":
			return .sxc
		case "stc":
			return .stc
		case "sxd":
			return .sxd
		case "std":
			return .std
		case "sxi":
			return .sxi
		case "sti":
			return .sti
		case "sxm":
			return .sxm
		case "sxw":
			return .sxw
		case "sxg":
			return .sxg
		case "stw":
			return .stw
		case "sus":
			return .sus
		case "susp":
			return .sus
		case "svd":
			return .svd
		case "sis":
			return .sis
		case "sisx":
			return .sis
		case "xsm":
			return .xsm
		case "bdm":
			return .bdm
		case "xdm":
			return .xdm
		case "tao":
			return .tao
		case "pcap":
			return .pcap
		case "cap":
			return .pcap
		case "dmp":
			return .pcap
		case "tmo":
			return .tmo
		case "tpt":
			return .tpt
		case "mxs":
			return .mxs
		case "tra":
			return .tra
		case "ufd":
			return .ufd
		case "ufdl":
			return .ufd
		case "utz":
			return .utz
		case "umj":
			return .umj
		case "unityweb":
			return .unityweb
		case "uoml":
			return .uoml
		case "vcx":
			return .vcx
		case "vsd":
			return .vsd
		case "vst":
			return .vsd
		case "vss":
			return .vsd
		case "vsw":
			return .vsd
		case "vis":
			return .vis
		case "vsf":
			return .vsf
		case "wbxml":
			return .wbxml
		case "wmlc":
			return .wmlc
		case "wmlsc":
			return .wmlsc
		case "wtb":
			return .wtb
		case "nbp":
			return .nbp
		case "wpd":
			return .wpd
		case "wqd":
			return .wqd
		case "stf":
			return .stf
		case "xar":
			return .xar
		case "xfdl":
			return .xfdl
		case "hvd":
			return .hvd
		case "hvs":
			return .hvs
		case "hvp":
			return .hvp
		case "osf":
			return .osf
		case "osfpvg":
			return .osfpvg
		case "saf":
			return .saf
		case "spf":
			return .spf
		case "cmp":
			return .cmp
		case "zir":
			return .zir
		case "zirz":
			return .zir
		case "zaz":
			return .zaz
		case "vxml":
			return .vxml
		case "wgt":
			return .wgt
		case "hlp":
			return .hlp
		case "wsdl":
			return .wsdl
		case "wspolicy":
			return .wspolicy
		case "7z":
			return ._7z
		case "abw":
			return .abw
		case "ace":
			return .ace
		case "dmg":
			return .dmg
		case "aab":
			return .aab
		case "x32":
			return .aab
		case "u32":
			return .aab
		case "vox":
			return .aab
		case "aam":
			return .aam
		case "aas":
			return .aas
		case "bcpio":
			return .bcpio
		case "torrent":
			return .torrent
		case "blb":
			return .blb
		case "blorb":
			return .blb
		case "bz":
			return .bz
		case "bz2":
			return .bz2
		case "boz":
			return .bz2
		case "cbr":
			return .cbr
		case "cba":
			return .cbr
		case "cbt":
			return .cbr
		case "cbz":
			return .cbr
		case "cb7":
			return .cbr
		case "vcd":
			return .vcd
		case "cfs":
			return .cfs
		case "chat":
			return .chat
		case "pgn":
			return .pgn
		case "nsc":
			return .nsc
		case "cpio":
			return .cpio
		case "csh":
			return .csh
		case "deb":
			return .deb
		case "udeb":
			return .deb
		case "dgc":
			return .dgc
		case "dir":
			return .dir
		case "dcr":
			return .dir
		case "dxr":
			return .dir
		case "cst":
			return .dir
		case "cct":
			return .dir
		case "cxt":
			return .dir
		case "w3d":
			return .dir
		case "fgd":
			return .dir
		case "swa":
			return .dir
		case "wad":
			return .wad
		case "ncx":
			return .ncx
		case "dtb":
			return .dtb
		case "res":
			return .res
		case "dvi":
			return .dvi
		case "evy":
			return .evy
		case "eva":
			return .eva
		case "bdf":
			return .bdf
		case "gsf":
			return .gsf
		case "psf":
			return .psf
		case "pcf":
			return .pcf
		case "snf":
			return .snf
		case "pfa":
			return .pfa
		case "pfb":
			return .pfa
		case "pfm":
			return .pfa
		case "afm":
			return .pfa
		case "arc":
			return .arc
		case "spl":
			return .spl
		case "gca":
			return .gca
		case "ulx":
			return .ulx
		case "gnumeric":
			return .gnumeric
		case "gramps":
			return .gramps
		case "gtar":
			return .gtar
		case "hdf":
			return .hdf
		case "install":
			return .install
		case "iso":
			return .iso
		case "jnlp":
			return .jnlp
		case "latex":
			return .latex
		case "lzh":
			return .lzh
		case "lha":
			return .lzh
		case "mie":
			return .mie
		case "prc":
			return .prc
		case "mobi":
			return .prc
		case "application":
			return .application
		case "lnk":
			return .lnk
		case "wmd":
			return .wmd
		case "wmz":
			return .wmz
		case "xbap":
			return .xbap
		case "mdb":
			return .mdb
		case "obd":
			return .obd
		case "crd":
			return .crd
		case "clp":
			return .clp
		case "exe":
			return .exe
		case "dll":
			return .exe
		case "com":
			return .exe
		case "bat":
			return .exe
		case "msi":
			return .exe
		case "mvb":
			return .mvb
		case "m13":
			return .mvb
		case "m14":
			return .mvb
		case "wmf":
			return .wmf
		case "emf":
			return .wmf
		case "emz":
			return .wmf
		case "mny":
			return .mny
		case "pub":
			return .pub
		case "scd":
			return .scd
		case "trm":
			return .trm
		case "wri":
			return .wri
		case "nc":
			return .nc
		case "cdf":
			return .nc
		case "nzb":
			return .nzb
		case "p12":
			return .p12
		case "pfx":
			return .p12
		case "p7b":
			return .p7b
		case "spc":
			return .p7b
		case "p7r":
			return .p7r
		case "rar":
			return .rar
		case "ris":
			return .ris
		case "sh":
			return .sh
		case "shar":
			return .shar
		case "swf":
			return .swf
		case "xap":
			return .xap
		case "sql":
			return .sql
		case "sit":
			return .sit
		case "sitx":
			return .sitx
		case "srt":
			return .srt
		case "sv4cpio":
			return .sv4cpio
		case "sv4crc":
			return .sv4crc
		case "t3":
			return .t3
		case "gam":
			return .gam
		case "tar":
			return .tar
		case "tcl":
			return .tcl
		case "tex":
			return .tex
		case "tfm":
			return .tfm
		case "texinfo":
			return .texinfo
		case "texi":
			return .texinfo
		case "obj":
			return .obj
		case "ustar":
			return .ustar
		case "src":
			return .src
		case "der":
			return .der
		case "crt":
			return .der
		case "fig":
			return .fig
		case "xlf":
			return .xlf
		case "xpi":
			return .xpi
		case "xz":
			return .xz
		case "z1":
			return .z1
		case "z2":
			return .z1
		case "z3":
			return .z1
		case "z4":
			return .z1
		case "z5":
			return .z1
		case "z6":
			return .z1
		case "z7":
			return .z1
		case "z8":
			return .z1
		case "xaml":
			return .xaml
		case "xdf":
			return .xdf
		case "xenc":
			return .xenc
		case "xhtml":
			return .xhtml
		case "xht":
			return .xhtml
		case "xml":
			return .xml
		case "xsl":
			return .xml
		case "dtd":
			return .dtd
		case "xop":
			return .xop
		case "xpl":
			return .xpl
		case "xslt":
			return .xslt
		case "xspf":
			return .xspf
		case "mxml":
			return .mxml
		case "xhvml":
			return .mxml
		case "xvml":
			return .mxml
		case "xvm":
			return .mxml
		case "yang":
			return .yang
		case "yin":
			return .yin
		case "zip":
			return .zip
		case "adp":
			return .adp
		case "au":
			return .au
		case "snd":
			return .au
		case "mid":
			return .mid
		case "midi":
			return .mid
		case "kar":
			return .mid
		case "rmi":
			return .mid
		case "m4a":
			return .m4a
		case "mp4a":
			return .m4a
		case "mpga":
			return .mpga
		case "mp2":
			return .mpga
		case "mp2a":
			return .mpga
		case "mp3":
			return .mpga
		case "m2a":
			return .mpga
		case "m3a":
			return .mpga
		case "oga":
			return .oga
		case "ogg":
			return .oga
		case "spx":
			return .oga
		case "s3m":
			return .s3m
		case "sil":
			return .sil
		case "uva":
			return .uva
		case "uvva":
			return .uva
		case "eol":
			return .eol
		case "dra":
			return .dra
		case "dts":
			return .dts
		case "dtshd":
			return .dtshd
		case "lvp":
			return .lvp
		case "pya":
			return .pya
		case "ecelp4800":
			return .ecelp4800
		case "ecelp7470":
			return .ecelp7470
		case "ecelp9600":
			return .ecelp9600
		case "rip":
			return .rip
		case "weba":
			return .weba
		case "aac":
			return .aac
		case "aif":
			return .aif
		case "aiff":
			return .aif
		case "aifc":
			return .aif
		case "caf":
			return .caf
		case "flac":
			return .flac
		case "mka":
			return .mka
		case "m3u":
			return .m3u
		case "wax":
			return .wax
		case "wma":
			return .wma
		case "ram":
			return .ram
		case "ra":
			return .ram
		case "rmp":
			return .rmp
		case "wav":
			return .wav
		case "xm":
			return .xm
		case "cdx":
			return .cdx
		case "cif":
			return .cif
		case "cmdf":
			return .cmdf
		case "cml":
			return .cml
		case "csml":
			return .csml
		case "xyz":
			return .xyz
		case "ttc":
			return .ttc
		case "otf":
			return .otf
		case "ttf":
			return .ttf
		case "woff":
			return .woff
		case "woff2":
			return .woff2
		case "bmp":
			return .bmp
		case "cgm":
			return .cgm
		case "g3":
			return .g3
		case "gif":
			return .gif
		case "ief":
			return .ief
		case "jpeg":
			return .jpeg
		case "jpg":
			return .jpeg
		case "jpe":
			return .jpeg
		case "ktx":
			return .ktx
		case "png":
			return .png
		case "btif":
			return .btif
		case "sgi":
			return .sgi
		case "svg":
			return .svg
		case "svgz":
			return .svg
		case "tiff":
			return .tiff
		case "tif":
			return .tiff
		case "psd":
			return .psd
		case "uvi":
			return .uvi
		case "uvvi":
			return .uvi
		case "uvg":
			return .uvi
		case "uvvg":
			return .uvi
		case "djvu":
			return .djvu
		case "djv":
			return .djvu
		case "sub":
			return .sub
		case "dwg":
			return .dwg
		case "dxf":
			return .dxf
		case "fbs":
			return .fbs
		case "fpx":
			return .fpx
		case "fst":
			return .fst
		case "mmr":
			return .mmr
		case "rlc":
			return .rlc
		case "mdi":
			return .mdi
		case "wdp":
			return .wdp
		case "npx":
			return .npx
		case "wbmp":
			return .wbmp
		case "xif":
			return .xif
		case "webp":
			return .webp
		case "3ds":
			return ._3ds
		case "ras":
			return .ras
		case "cmx":
			return .cmx
		case "fh":
			return .fh
		case "fhc":
			return .fh
		case "fh4":
			return .fh
		case "fh5":
			return .fh
		case "fh7":
			return .fh
		case "ico":
			return .ico
		case "sid":
			return .sid
		case "pcx":
			return .pcx
		case "pic":
			return .pic
		case "pct":
			return .pic
		case "pnm":
			return .pnm
		case "pbm":
			return .pbm
		case "pgm":
			return .pgm
		case "ppm":
			return .ppm
		case "rgb":
			return .rgb
		case "tga":
			return .tga
		case "xbm":
			return .xbm
		case "xpm":
			return .xpm
		case "xwd":
			return .xwd
		case "eml":
			return .eml
		case "mime":
			return .eml
		case "igs":
			return .igs
		case "iges":
			return .igs
		case "msh":
			return .msh
		case "mesh":
			return .msh
		case "silo":
			return .msh
		case "dae":
			return .dae
		case "dwf":
			return .dwf
		case "gdl":
			return .gdl
		case "gtw":
			return .gtw
		case "mts":
			return .mts
		case "vtu":
			return .vtu
		case "wrl":
			return .wrl
		case "vrml":
			return .wrl
		case "x3db":
			return .x3db
		case "x3dbz":
			return .x3db
		case "x3dv":
			return .x3dv
		case "x3dvz":
			return .x3dv
		case "x3d":
			return .x3d
		case "x3dz":
			return .x3d
		case "appcache":
			return .appcache
		case "ics":
			return .ics
		case "ifb":
			return .ics
		case "css":
			return .css
		case "csv":
			return .csv
		case "html":
			return .html
		case "htm":
			return .html
		case "n3":
			return .n3
		case "txt":
			return .txt
		case "text":
			return .txt
		case "conf":
			return .txt
		case "def":
			return .txt
		case "list":
			return .txt
		case "log":
			return .txt
		case "in":
			return .txt
		case "dsc":
			return .dsc
		case "rtx":
			return .rtx
		case "sgml":
			return .sgml
		case "sgm":
			return .sgml
		case "tsv":
			return .tsv
		case "t":
			return .t
		case "tr":
			return .t
		case "roff":
			return .t
		case "man":
			return .t
		case "me":
			return .t
		case "ms":
			return .t
		case "ttl":
			return .ttl
		case "uri":
			return .uri
		case "uris":
			return .uri
		case "urls":
			return .uri
		case "vcard":
			return .vcard
		case "curl":
			return .curl
		case "dcurl":
			return .dcurl
		case "mcurl":
			return .mcurl
		case "scurl":
			return .scurl
		case "fly":
			return .fly
		case "flx":
			return .flx
		case "gv":
			return .gv
		case "3dml":
			return ._3dml
		case "spot":
			return .spot
		case "jad":
			return .jad
		case "wml":
			return .wml
		case "wmls":
			return .wmls
		case "s":
			return .s
		case "asm":
			return .s
		case "c":
			return .c
		case "cc":
			return .c
		case "cxx":
			return .c
		case "cpp":
			return .c
		case "h":
			return .c
		case "hh":
			return .c
		case "dic":
			return .c
		case "f":
			return .f
		case "for":
			return .f
		case "f77":
			return .f
		case "f90":
			return .f
		case "java":
			return .java
		case "nfo":
			return .nfo
		case "opml":
			return .opml
		case "p":
			return .p
		case "pas":
			return .p
		case "etx":
			return .etx
		case "sfv":
			return .sfv
		case "uu":
			return .uu
		case "vcs":
			return .vcs
		case "vcf":
			return .vcf
		case "3gp":
			return ._3gp
		case "3g2":
			return ._3g2
		case "h261":
			return .h261
		case "h263":
			return .h263
		case "h264":
			return .h264
		case "jpgv":
			return .jpgv
		case "jpm":
			return .jpm
		case "jpgm":
			return .jpm
		case "mj2":
			return .mj2
		case "mjp2":
			return .mj2
		case "mp4":
			return .mp4
		case "mp4v":
			return .mp4
		case "mpg4":
			return .mp4
		case "mpeg":
			return .mpeg
		case "mpg":
			return .mpeg
		case "mpe":
			return .mpeg
		case "m1v":
			return .mpeg
		case "m2v":
			return .mpeg
		case "ogv":
			return .ogv
		case "qt":
			return .qt
		case "mov":
			return .qt
		case "uvh":
			return .uvh
		case "uvvh":
			return .uvh
		case "uvm":
			return .uvm
		case "uvvm":
			return .uvm
		case "uvp":
			return .uvp
		case "uvvp":
			return .uvp
		case "uvs":
			return .uvs
		case "uvvs":
			return .uvs
		case "uvv":
			return .uvv
		case "uvvv":
			return .uvv
		case "dvb":
			return .dvb
		case "fvt":
			return .fvt
		case "mxu":
			return .mxu
		case "m4u":
			return .mxu
		case "pyv":
			return .pyv
		case "uvu":
			return .uvu
		case "uvvu":
			return .uvu
		case "viv":
			return .viv
		case "webm":
			return .webm
		case "f4v":
			return .f4v
		case "fli":
			return .fli
		case "flv":
			return .flv
		case "m4v":
			return .m4v
		case "mkv":
			return .mkv
		case "mk3d":
			return .mkv
		case "mks":
			return .mkv
		case "mng":
			return .mng
		case "asf":
			return .asf
		case "asx":
			return .asf
		case "vob":
			return .vob
		case "wm":
			return .wm
		case "wmv":
			return .wmv
		case "wmx":
			return .wmx
		case "wvx":
			return .wvx
		case "avi":
			return .avi
		case "movie":
			return .movie
		case "smv":
			return .smv
		case "ice":
			return .ice
		default:
			return nil
		}
	}

	public static func fileExtension(forMime mime: String) -> String? {
		switch mime {
		case "application/andrew-inset":
			return "ez"
		case "application/applixware":
			return "aw"
		case "application/atom+xml":
			return "atom"
		case "application/atomcat+xml":
			return "atomcat"
		case "application/atomsvc+xml":
			return "atomsvc"
		case "application/ccxml+xml":
			return "ccxml"
		case "application/cdmi-capability":
			return "cdmia"
		case "application/cdmi-container":
			return "cdmic"
		case "application/cdmi-domain":
			return "cdmid"
		case "application/cdmi-object":
			return "cdmio"
		case "application/cdmi-queue":
			return "cdmiq"
		case "application/cu-seeme":
			return "cu"
		case "application/davmount+xml":
			return "davmount"
		case "application/docbook+xml":
			return "dbk"
		case "application/dssc+der":
			return "dssc"
		case "application/dssc+xml":
			return "xdssc"
		case "application/ecmascript":
			return "ecma"
		case "application/emma+xml":
			return "emma"
		case "application/epub+zip":
			return "epub"
		case "application/exi":
			return "exi"
		case "application/font-tdpfr":
			return "pfr"
		case "application/gml+xml":
			return "gml"
		case "application/gpx+xml":
			return "gpx"
		case "application/gxf":
			return "gxf"
		case "application/hyperstudio":
			return "stk"
		case "application/inkml+xml":
			return "ink"
		case "application/ipfix":
			return "ipfix"
		case "application/java-archive":
			return "jar"
		case "application/java-serialized-object":
			return "ser"
		case "application/java-vm":
			return "class"
		case "application/javascript":
			return "js"
		case "application/json":
			return "json"
		case "application/jsonml+json":
			return "jsonml"
		case "application/lost+xml":
			return "lostxml"
		case "application/mac-binhex40":
			return "hqx"
		case "application/mac-compactpro":
			return "cpt"
		case "application/mads+xml":
			return "mads"
		case "application/marc":
			return "mrc"
		case "application/marcxml+xml":
			return "mrcx"
		case "application/mathematica":
			return "ma"
		case "application/mathml+xml":
			return "mathml"
		case "application/mbox":
			return "mbox"
		case "application/mediaservercontrol+xml":
			return "mscml"
		case "application/metalink+xml":
			return "metalink"
		case "application/metalink4+xml":
			return "meta4"
		case "application/mets+xml":
			return "mets"
		case "application/mods+xml":
			return "mods"
		case "application/mp21":
			return "m21"
		case "application/mp4":
			return "mp4s"
		case "application/msword":
			return "doc"
		case "application/mxf":
			return "mxf"
		case "application/octet-stream":
			return "bin"
		case "application/oda":
			return "oda"
		case "application/oebps-package+xml":
			return "opf"
		case "application/ogg":
			return "ogx"
		case "application/omdoc+xml":
			return "omdoc"
		case "application/onenote":
			return "onetoc"
		case "application/oxps":
			return "oxps"
		case "application/patch-ops-error+xml":
			return "xer"
		case "application/pdf":
			return "pdf"
		case "application/pgp-encrypted":
			return "pgp"
		case "application/pgp-signature":
			return "asc"
		case "application/pics-rules":
			return "prf"
		case "application/pkcs10":
			return "p10"
		case "application/pkcs7-mime":
			return "p7m"
		case "application/pkcs7-signature":
			return "p7s"
		case "application/pkcs8":
			return "p8"
		case "application/pkix-attr-cert":
			return "ac"
		case "application/pkix-cert":
			return "cer"
		case "application/pkix-crl":
			return "crl"
		case "application/pkix-pkipath":
			return "pkipath"
		case "application/pkixcmp":
			return "pki"
		case "application/pls+xml":
			return "pls"
		case "application/postscript":
			return "ai"
		case "application/prs.cww":
			return "cww"
		case "application/pskc+xml":
			return "pskcxml"
		case "application/rdf+xml":
			return "rdf"
		case "application/reginfo+xml":
			return "rif"
		case "application/relax-ng-compact-syntax":
			return "rnc"
		case "application/resource-lists+xml":
			return "rl"
		case "application/resource-lists-diff+xml":
			return "rld"
		case "application/rls-services+xml":
			return "rs"
		case "application/rpki-ghostbusters":
			return "gbr"
		case "application/rpki-manifest":
			return "mft"
		case "application/rpki-roa":
			return "roa"
		case "application/rsd+xml":
			return "rsd"
		case "application/rss+xml":
			return "rss"
		case "application/rtf":
			return "rtf"
		case "application/sbml+xml":
			return "sbml"
		case "application/scvp-cv-request":
			return "scq"
		case "application/scvp-cv-response":
			return "scs"
		case "application/scvp-vp-request":
			return "spq"
		case "application/scvp-vp-response":
			return "spp"
		case "application/sdp":
			return "sdp"
		case "application/set-payment-initiation":
			return "setpay"
		case "application/set-registration-initiation":
			return "setreg"
		case "application/shf+xml":
			return "shf"
		case "application/smil+xml":
			return "smi"
		case "application/sparql-query":
			return "rq"
		case "application/sparql-results+xml":
			return "srx"
		case "application/srgs":
			return "gram"
		case "application/srgs+xml":
			return "grxml"
		case "application/sru+xml":
			return "sru"
		case "application/ssdl+xml":
			return "ssdl"
		case "application/ssml+xml":
			return "ssml"
		case "application/tei+xml":
			return "tei"
		case "application/thraud+xml":
			return "tfi"
		case "application/timestamped-data":
			return "tsd"
		case "application/vnd.3gpp.pic-bw-large":
			return "plb"
		case "application/vnd.3gpp.pic-bw-small":
			return "psb"
		case "application/vnd.3gpp.pic-bw-var":
			return "pvb"
		case "application/vnd.3gpp2.tcap":
			return "tcap"
		case "application/vnd.3m.post-it-notes":
			return "pwn"
		case "application/vnd.accpac.simply.aso":
			return "aso"
		case "application/vnd.accpac.simply.imp":
			return "imp"
		case "application/vnd.acucobol":
			return "acu"
		case "application/vnd.acucorp":
			return "atc"
		case "application/vnd.adobe.air-application-installer-package+zip":
			return "air"
		case "application/vnd.adobe.formscentral.fcdt":
			return "fcdt"
		case "application/vnd.adobe.fxp":
			return "fxp"
		case "application/vnd.adobe.xdp+xml":
			return "xdp"
		case "application/vnd.adobe.xfdf":
			return "xfdf"
		case "application/vnd.ahead.space":
			return "ahead"
		case "application/vnd.airzip.filesecure.azf":
			return "azf"
		case "application/vnd.airzip.filesecure.azs":
			return "azs"
		case "application/vnd.amazon.ebook":
			return "azw"
		case "application/vnd.americandynamics.acc":
			return "acc"
		case "application/vnd.amiga.ami":
			return "ami"
		case "application/vnd.android.package-archive":
			return "apk"
		case "application/vnd.anser-web-certificate-issue-initiation":
			return "cii"
		case "application/vnd.anser-web-funds-transfer-initiation":
			return "fti"
		case "application/vnd.antix.game-component":
			return "atx"
		case "application/vnd.apple.installer+xml":
			return "mpkg"
		case "application/vnd.apple.mpegurl":
			return "m3u8"
		case "application/vnd.aristanetworks.swi":
			return "swi"
		case "application/vnd.astraea-software.iota":
			return "iota"
		case "application/vnd.audiograph":
			return "aep"
		case "application/vnd.blueice.multipass":
			return "mpm"
		case "application/vnd.bmi":
			return "bmi"
		case "application/vnd.businessobjects":
			return "rep"
		case "application/vnd.chemdraw+xml":
			return "cdxml"
		case "application/vnd.chipnuts.karaoke-mmd":
			return "mmd"
		case "application/vnd.cinderella":
			return "cdy"
		case "application/vnd.claymore":
			return "cla"
		case "application/vnd.cloanto.rp9":
			return "rp9"
		case "application/vnd.clonk.c4group":
			return "c4g"
		case "application/vnd.cluetrust.cartomobile-config":
			return "c11amc"
		case "application/vnd.cluetrust.cartomobile-config-pkg":
			return "c11amz"
		case "application/vnd.commonspace":
			return "csp"
		case "application/vnd.contact.cmsg":
			return "cdbcmsg"
		case "application/vnd.cosmocaller":
			return "cmc"
		case "application/vnd.crick.clicker":
			return "clkx"
		case "application/vnd.crick.clicker.keyboard":
			return "clkk"
		case "application/vnd.crick.clicker.palette":
			return "clkp"
		case "application/vnd.crick.clicker.template":
			return "clkt"
		case "application/vnd.crick.clicker.wordbank":
			return "clkw"
		case "application/vnd.criticaltools.wbs+xml":
			return "wbs"
		case "application/vnd.ctc-posml":
			return "pml"
		case "application/vnd.cups-ppd":
			return "ppd"
		case "application/vnd.curl.car":
			return "car"
		case "application/vnd.curl.pcurl":
			return "pcurl"
		case "application/vnd.dart":
			return "dart"
		case "application/vnd.data-vision.rdz":
			return "rdz"
		case "application/vnd.dece.data":
			return "uvf"
		case "application/vnd.dece.ttml+xml":
			return "uvt"
		case "application/vnd.dece.unspecified":
			return "uvx"
		case "application/vnd.dece.zip":
			return "uvz"
		case "application/vnd.denovo.fcselayout-link":
			return "fe_launch"
		case "application/vnd.dna":
			return "dna"
		case "application/vnd.dolby.mlp":
			return "mlp"
		case "application/vnd.dpgraph":
			return "dpg"
		case "application/vnd.dreamfactory":
			return "dfac"
		case "application/vnd.ds-keypoint":
			return "kpxx"
		case "application/vnd.dvb.ait":
			return "ait"
		case "application/vnd.dvb.service":
			return "svc"
		case "application/vnd.dynageo":
			return "geo"
		case "application/vnd.ecowin.chart":
			return "mag"
		case "application/vnd.enliven":
			return "nml"
		case "application/vnd.epson.esf":
			return "esf"
		case "application/vnd.epson.msf":
			return "msf"
		case "application/vnd.epson.quickanime":
			return "qam"
		case "application/vnd.epson.salt":
			return "slt"
		case "application/vnd.epson.ssf":
			return "ssf"
		case "application/vnd.eszigno3+xml":
			return "es3"
		case "application/vnd.ezpix-album":
			return "ez2"
		case "application/vnd.ezpix-package":
			return "ez3"
		case "application/vnd.fdf":
			return "fdf"
		case "application/vnd.fdsn.mseed":
			return "mseed"
		case "application/vnd.fdsn.seed":
			return "seed"
		case "application/vnd.flographit":
			return "gph"
		case "application/vnd.fluxtime.clip":
			return "ftc"
		case "application/vnd.framemaker":
			return "fm"
		case "application/vnd.frogans.fnc":
			return "fnc"
		case "application/vnd.frogans.ltf":
			return "ltf"
		case "application/vnd.fsc.weblaunch":
			return "fsc"
		case "application/vnd.fujitsu.oasys":
			return "oas"
		case "application/vnd.fujitsu.oasys2":
			return "oa2"
		case "application/vnd.fujitsu.oasys3":
			return "oa3"
		case "application/vnd.fujitsu.oasysgp":
			return "fg5"
		case "application/vnd.fujitsu.oasysprs":
			return "bh2"
		case "application/vnd.fujixerox.ddd":
			return "ddd"
		case "application/vnd.fujixerox.docuworks":
			return "xdw"
		case "application/vnd.fujixerox.docuworks.binder":
			return "xbd"
		case "application/vnd.fuzzysheet":
			return "fzs"
		case "application/vnd.genomatix.tuxedo":
			return "txd"
		case "application/vnd.geogebra.file":
			return "ggb"
		case "application/vnd.geogebra.tool":
			return "ggt"
		case "application/vnd.geometry-explorer":
			return "gex"
		case "application/vnd.geonext":
			return "gxt"
		case "application/vnd.geoplan":
			return "g2w"
		case "application/vnd.geospace":
			return "g3w"
		case "application/vnd.gmx":
			return "gmx"
		case "application/vnd.google-earth.kml+xml":
			return "kml"
		case "application/vnd.google-earth.kmz":
			return "kmz"
		case "application/vnd.grafeq":
			return "gqf"
		case "application/vnd.groove-account":
			return "gac"
		case "application/vnd.groove-help":
			return "ghf"
		case "application/vnd.groove-identity-message":
			return "gim"
		case "application/vnd.groove-injector":
			return "grv"
		case "application/vnd.groove-tool-message":
			return "gtm"
		case "application/vnd.groove-tool-template":
			return "tpl"
		case "application/vnd.groove-vcard":
			return "vcg"
		case "application/vnd.hal+xml":
			return "hal"
		case "application/vnd.handheld-entertainment+xml":
			return "zmm"
		case "application/vnd.hbci":
			return "hbci"
		case "application/vnd.hhe.lesson-player":
			return "les"
		case "application/vnd.hp-hpgl":
			return "hpgl"
		case "application/vnd.hp-hpid":
			return "hpid"
		case "application/vnd.hp-hps":
			return "hps"
		case "application/vnd.hp-jlyt":
			return "jlt"
		case "application/vnd.hp-pcl":
			return "pcl"
		case "application/vnd.hp-pclxl":
			return "pclxl"
		case "application/vnd.hydrostatix.sof-data":
			return "sfd-hdstx"
		case "application/vnd.ibm.minipay":
			return "mpy"
		case "application/vnd.ibm.modcap":
			return "afp"
		case "application/vnd.ibm.rights-management":
			return "irm"
		case "application/vnd.ibm.secure-container":
			return "sc"
		case "application/vnd.iccprofile":
			return "icc"
		case "application/vnd.igloader":
			return "igl"
		case "application/vnd.immervision-ivp":
			return "ivp"
		case "application/vnd.immervision-ivu":
			return "ivu"
		case "application/vnd.insors.igm":
			return "igm"
		case "application/vnd.intercon.formnet":
			return "xpw"
		case "application/vnd.intergeo":
			return "i2g"
		case "application/vnd.intu.qbo":
			return "qbo"
		case "application/vnd.intu.qfx":
			return "qfx"
		case "application/vnd.ipunplugged.rcprofile":
			return "rcprofile"
		case "application/vnd.irepository.package+xml":
			return "irp"
		case "application/vnd.is-xpr":
			return "xpr"
		case "application/vnd.isac.fcs":
			return "fcs"
		case "application/vnd.jam":
			return "jam"
		case "application/vnd.jcp.javame.midlet-rms":
			return "rms"
		case "application/vnd.jisp":
			return "jisp"
		case "application/vnd.joost.joda-archive":
			return "joda"
		case "application/vnd.kahootz":
			return "ktz"
		case "application/vnd.kde.karbon":
			return "karbon"
		case "application/vnd.kde.kchart":
			return "chrt"
		case "application/vnd.kde.kformula":
			return "kfo"
		case "application/vnd.kde.kivio":
			return "flw"
		case "application/vnd.kde.kontour":
			return "kon"
		case "application/vnd.kde.kpresenter":
			return "kpr"
		case "application/vnd.kde.kspread":
			return "ksp"
		case "application/vnd.kde.kword":
			return "kwd"
		case "application/vnd.kenameaapp":
			return "htke"
		case "application/vnd.kidspiration":
			return "kia"
		case "application/vnd.kinar":
			return "kne"
		case "application/vnd.koan":
			return "skp"
		case "application/vnd.kodak-descriptor":
			return "sse"
		case "application/vnd.las.las+xml":
			return "lasxml"
		case "application/vnd.llamagraphics.life-balance.desktop":
			return "lbd"
		case "application/vnd.llamagraphics.life-balance.exchange+xml":
			return "lbe"
		case "application/vnd.lotus-1-2-3":
			return "123"
		case "application/vnd.lotus-approach":
			return "apr"
		case "application/vnd.lotus-freelance":
			return "pre"
		case "application/vnd.lotus-notes":
			return "nsf"
		case "application/vnd.lotus-organizer":
			return "org"
		case "application/vnd.lotus-screencam":
			return "scm"
		case "application/vnd.lotus-wordpro":
			return "lwp"
		case "application/vnd.macports.portpkg":
			return "portpkg"
		case "application/vnd.mcd":
			return "mcd"
		case "application/vnd.medcalcdata":
			return "mc1"
		case "application/vnd.mediastation.cdkey":
			return "cdkey"
		case "application/vnd.mfer":
			return "mwf"
		case "application/vnd.mfmp":
			return "mfm"
		case "application/vnd.micrografx.flo":
			return "flo"
		case "application/vnd.micrografx.igx":
			return "igx"
		case "application/vnd.mif":
			return "mif"
		case "application/vnd.mobius.daf":
			return "daf"
		case "application/vnd.mobius.dis":
			return "dis"
		case "application/vnd.mobius.mbk":
			return "mbk"
		case "application/vnd.mobius.mqy":
			return "mqy"
		case "application/vnd.mobius.msl":
			return "msl"
		case "application/vnd.mobius.plc":
			return "plc"
		case "application/vnd.mobius.txf":
			return "txf"
		case "application/vnd.mophun.application":
			return "mpn"
		case "application/vnd.mophun.certificate":
			return "mpc"
		case "application/vnd.mozilla.xul+xml":
			return "xul"
		case "application/vnd.ms-artgalry":
			return "cil"
		case "application/vnd.ms-cab-compressed":
			return "cab"
		case "application/vnd.ms-excel":
			return "xls"
		case "application/vnd.ms-excel.addin.macroenabled.12":
			return "xlam"
		case "application/vnd.ms-excel.sheet.binary.macroenabled.12":
			return "xlsb"
		case "application/vnd.ms-excel.sheet.macroenabled.12":
			return "xlsm"
		case "application/vnd.ms-excel.template.macroenabled.12":
			return "xltm"
		case "application/vnd.ms-fontobject":
			return "eot"
		case "application/vnd.ms-htmlhelp":
			return "chm"
		case "application/vnd.ms-ims":
			return "ims"
		case "application/vnd.ms-lrm":
			return "lrm"
		case "application/vnd.ms-officetheme":
			return "thmx"
		case "application/vnd.ms-pki.seccat":
			return "cat"
		case "application/vnd.ms-pki.stl":
			return "stl"
		case "application/vnd.ms-powerpoint":
			return "ppt"
		case "application/vnd.ms-powerpoint.addin.macroenabled.12":
			return "ppam"
		case "application/vnd.ms-powerpoint.presentation.macroenabled.12":
			return "pptm"
		case "application/vnd.ms-powerpoint.slide.macroenabled.12":
			return "sldm"
		case "application/vnd.ms-powerpoint.slideshow.macroenabled.12":
			return "ppsm"
		case "application/vnd.ms-powerpoint.template.macroenabled.12":
			return "potm"
		case "application/vnd.ms-project":
			return "mpp"
		case "application/vnd.ms-word.document.macroenabled.12":
			return "docm"
		case "application/vnd.ms-word.template.macroenabled.12":
			return "dotm"
		case "application/vnd.ms-works":
			return "wps"
		case "application/vnd.ms-wpl":
			return "wpl"
		case "application/vnd.ms-xpsdocument":
			return "xps"
		case "application/vnd.mseq":
			return "mseq"
		case "application/vnd.musician":
			return "mus"
		case "application/vnd.muvee.style":
			return "msty"
		case "application/vnd.mynfc":
			return "taglet"
		case "application/vnd.neurolanguage.nlu":
			return "nlu"
		case "application/vnd.nitf":
			return "ntf"
		case "application/vnd.noblenet-directory":
			return "nnd"
		case "application/vnd.noblenet-sealer":
			return "nns"
		case "application/vnd.noblenet-web":
			return "nnw"
		case "application/vnd.nokia.n-gage.data":
			return "ngdat"
		case "application/vnd.nokia.n-gage.symbian.install":
			return "n-gage"
		case "application/vnd.nokia.radio-preset":
			return "rpst"
		case "application/vnd.nokia.radio-presets":
			return "rpss"
		case "application/vnd.novadigm.edm":
			return "edm"
		case "application/vnd.novadigm.edx":
			return "edx"
		case "application/vnd.novadigm.ext":
			return "ext"
		case "application/vnd.oasis.opendocument.chart":
			return "odc"
		case "application/vnd.oasis.opendocument.chart-template":
			return "otc"
		case "application/vnd.oasis.opendocument.database":
			return "odb"
		case "application/vnd.oasis.opendocument.formula":
			return "odf"
		case "application/vnd.oasis.opendocument.formula-template":
			return "odft"
		case "application/vnd.oasis.opendocument.graphics":
			return "odg"
		case "application/vnd.oasis.opendocument.graphics-template":
			return "otg"
		case "application/vnd.oasis.opendocument.image":
			return "odi"
		case "application/vnd.oasis.opendocument.image-template":
			return "oti"
		case "application/vnd.oasis.opendocument.presentation":
			return "odp"
		case "application/vnd.oasis.opendocument.presentation-template":
			return "otp"
		case "application/vnd.oasis.opendocument.spreadsheet":
			return "ods"
		case "application/vnd.oasis.opendocument.spreadsheet-template":
			return "ots"
		case "application/vnd.oasis.opendocument.text":
			return "odt"
		case "application/vnd.oasis.opendocument.text-master":
			return "odm"
		case "application/vnd.oasis.opendocument.text-template":
			return "ott"
		case "application/vnd.oasis.opendocument.text-web":
			return "oth"
		case "application/vnd.olpc-sugar":
			return "xo"
		case "application/vnd.oma.dd2+xml":
			return "dd2"
		case "application/vnd.openofficeorg.extension":
			return "oxt"
		case "application/vnd.openxmlformats-officedocument.presentationml.presentation":
			return "pptx"
		case "application/vnd.openxmlformats-officedocument.presentationml.slide":
			return "sldx"
		case "application/vnd.openxmlformats-officedocument.presentationml.slideshow":
			return "ppsx"
		case "application/vnd.openxmlformats-officedocument.presentationml.template":
			return "potx"
		case "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":
			return "xlsx"
		case "application/vnd.openxmlformats-officedocument.spreadsheetml.template":
			return "xltx"
		case "application/vnd.openxmlformats-officedocument.wordprocessingml.document":
			return "docx"
		case "application/vnd.openxmlformats-officedocument.wordprocessingml.template":
			return "dotx"
		case "application/vnd.osgeo.mapguide.package":
			return "mgp"
		case "application/vnd.osgi.dp":
			return "dp"
		case "application/vnd.osgi.subsystem":
			return "esa"
		case "application/vnd.palm":
			return "pdb"
		case "application/vnd.pawaafile":
			return "paw"
		case "application/vnd.pg.format":
			return "str"
		case "application/vnd.pg.osasli":
			return "ei6"
		case "application/vnd.picsel":
			return "efif"
		case "application/vnd.pmi.widget":
			return "wg"
		case "application/vnd.pocketlearn":
			return "plf"
		case "application/vnd.powerbuilder6":
			return "pbd"
		case "application/vnd.previewsystems.box":
			return "box"
		case "application/vnd.proteus.magazine":
			return "mgz"
		case "application/vnd.publishare-delta-tree":
			return "qps"
		case "application/vnd.pvi.ptid1":
			return "ptid"
		case "application/vnd.quark.quarkxpress":
			return "qxd"
		case "application/vnd.realvnc.bed":
			return "bed"
		case "application/vnd.recordare.musicxml":
			return "mxl"
		case "application/vnd.recordare.musicxml+xml":
			return "musicxml"
		case "application/vnd.rig.cryptonote":
			return "cryptonote"
		case "application/vnd.rim.cod":
			return "cod"
		case "application/vnd.rn-realmedia":
			return "rm"
		case "application/vnd.rn-realmedia-vbr":
			return "rmvb"
		case "application/vnd.route66.link66+xml":
			return "link66"
		case "application/vnd.sailingtracker.track":
			return "st"
		case "application/vnd.seemail":
			return "see"
		case "application/vnd.sema":
			return "sema"
		case "application/vnd.semd":
			return "semd"
		case "application/vnd.semf":
			return "semf"
		case "application/vnd.shana.informed.formdata":
			return "ifm"
		case "application/vnd.shana.informed.formtemplate":
			return "itp"
		case "application/vnd.shana.informed.interchange":
			return "iif"
		case "application/vnd.shana.informed.package":
			return "ipk"
		case "application/vnd.simtech-mindmapper":
			return "twd"
		case "application/vnd.smaf":
			return "mmf"
		case "application/vnd.smart.teacher":
			return "teacher"
		case "application/vnd.solent.sdkm+xml":
			return "sdkm"
		case "application/vnd.spotfire.dxp":
			return "dxp"
		case "application/vnd.spotfire.sfs":
			return "sfs"
		case "application/vnd.stardivision.calc":
			return "sdc"
		case "application/vnd.stardivision.draw":
			return "sda"
		case "application/vnd.stardivision.impress":
			return "sdd"
		case "application/vnd.stardivision.math":
			return "smf"
		case "application/vnd.stardivision.writer":
			return "sdw"
		case "application/vnd.stardivision.writer-global":
			return "sgl"
		case "application/vnd.stepmania.package":
			return "smzip"
		case "application/vnd.stepmania.stepchart":
			return "sm"
		case "application/vnd.sun.xml.calc":
			return "sxc"
		case "application/vnd.sun.xml.calc.template":
			return "stc"
		case "application/vnd.sun.xml.draw":
			return "sxd"
		case "application/vnd.sun.xml.draw.template":
			return "std"
		case "application/vnd.sun.xml.impress":
			return "sxi"
		case "application/vnd.sun.xml.impress.template":
			return "sti"
		case "application/vnd.sun.xml.math":
			return "sxm"
		case "application/vnd.sun.xml.writer":
			return "sxw"
		case "application/vnd.sun.xml.writer.global":
			return "sxg"
		case "application/vnd.sun.xml.writer.template":
			return "stw"
		case "application/vnd.sus-calendar":
			return "sus"
		case "application/vnd.svd":
			return "svd"
		case "application/vnd.symbian.install":
			return "sis"
		case "application/vnd.syncml+xml":
			return "xsm"
		case "application/vnd.syncml.dm+wbxml":
			return "bdm"
		case "application/vnd.syncml.dm+xml":
			return "xdm"
		case "application/vnd.tao.intent-module-archive":
			return "tao"
		case "application/vnd.tcpdump.pcap":
			return "pcap"
		case "application/vnd.tmobile-livetv":
			return "tmo"
		case "application/vnd.trid.tpt":
			return "tpt"
		case "application/vnd.triscape.mxs":
			return "mxs"
		case "application/vnd.trueapp":
			return "tra"
		case "application/vnd.ufdl":
			return "ufd"
		case "application/vnd.uiq.theme":
			return "utz"
		case "application/vnd.umajin":
			return "umj"
		case "application/vnd.unity":
			return "unityweb"
		case "application/vnd.uoml+xml":
			return "uoml"
		case "application/vnd.vcx":
			return "vcx"
		case "application/vnd.visio":
			return "vsd"
		case "application/vnd.visionary":
			return "vis"
		case "application/vnd.vsf":
			return "vsf"
		case "application/vnd.wap.wbxml":
			return "wbxml"
		case "application/vnd.wap.wmlc":
			return "wmlc"
		case "application/vnd.wap.wmlscriptc":
			return "wmlsc"
		case "application/vnd.webturbo":
			return "wtb"
		case "application/vnd.wolfram.player":
			return "nbp"
		case "application/vnd.wordperfect":
			return "wpd"
		case "application/vnd.wqd":
			return "wqd"
		case "application/vnd.wt.stf":
			return "stf"
		case "application/vnd.xara":
			return "xar"
		case "application/vnd.xfdl":
			return "xfdl"
		case "application/vnd.yamaha.hv-dic":
			return "hvd"
		case "application/vnd.yamaha.hv-script":
			return "hvs"
		case "application/vnd.yamaha.hv-voice":
			return "hvp"
		case "application/vnd.yamaha.openscoreformat":
			return "osf"
		case "application/vnd.yamaha.openscoreformat.osfpvg+xml":
			return "osfpvg"
		case "application/vnd.yamaha.smaf-audio":
			return "saf"
		case "application/vnd.yamaha.smaf-phrase":
			return "spf"
		case "application/vnd.yellowriver-custom-menu":
			return "cmp"
		case "application/vnd.zul":
			return "zir"
		case "application/vnd.zzazz.deck+xml":
			return "zaz"
		case "application/voicexml+xml":
			return "vxml"
		case "application/widget":
			return "wgt"
		case "application/winhlp":
			return "hlp"
		case "application/wsdl+xml":
			return "wsdl"
		case "application/wspolicy+xml":
			return "wspolicy"
		case "application/x-7z-compressed":
			return "7z"
		case "application/x-abiword":
			return "abw"
		case "application/x-ace-compressed":
			return "ace"
		case "application/x-apple-diskimage":
			return "dmg"
		case "application/x-authorware-bin":
			return "aab"
		case "application/x-authorware-map":
			return "aam"
		case "application/x-authorware-seg":
			return "aas"
		case "application/x-bcpio":
			return "bcpio"
		case "application/x-bittorrent":
			return "torrent"
		case "application/x-blorb":
			return "blb"
		case "application/x-bzip":
			return "bz"
		case "application/x-bzip2":
			return "bz2"
		case "application/x-cbr":
			return "cbr"
		case "application/x-cdlink":
			return "vcd"
		case "application/x-cfs-compressed":
			return "cfs"
		case "application/x-chat":
			return "chat"
		case "application/x-chess-pgn":
			return "pgn"
		case "application/x-conference":
			return "nsc"
		case "application/x-cpio":
			return "cpio"
		case "application/x-csh":
			return "csh"
		case "application/x-debian-package":
			return "deb"
		case "application/x-dgc-compressed":
			return "dgc"
		case "application/x-director":
			return "dir"
		case "application/x-doom":
			return "wad"
		case "application/x-dtbncx+xml":
			return "ncx"
		case "application/x-dtbook+xml":
			return "dtb"
		case "application/x-dtbresource+xml":
			return "res"
		case "application/x-dvi":
			return "dvi"
		case "application/x-envoy":
			return "evy"
		case "application/x-eva":
			return "eva"
		case "application/x-font-bdf":
			return "bdf"
		case "application/x-font-ghostscript":
			return "gsf"
		case "application/x-font-linux-psf":
			return "psf"
		case "application/x-font-pcf":
			return "pcf"
		case "application/x-font-snf":
			return "snf"
		case "application/x-font-type1":
			return "pfa"
		case "application/x-freearc":
			return "arc"
		case "application/x-futuresplash":
			return "spl"
		case "application/x-gca-compressed":
			return "gca"
		case "application/x-glulx":
			return "ulx"
		case "application/x-gnumeric":
			return "gnumeric"
		case "application/x-gramps-xml":
			return "gramps"
		case "application/x-gtar":
			return "gtar"
		case "application/x-hdf":
			return "hdf"
		case "application/x-install-instructions":
			return "install"
		case "application/x-iso9660-image":
			return "iso"
		case "application/x-java-jnlp-file":
			return "jnlp"
		case "application/x-latex":
			return "latex"
		case "application/x-lzh-compressed":
			return "lzh"
		case "application/x-mie":
			return "mie"
		case "application/x-mobipocket-ebook":
			return "prc"
		case "application/x-ms-application":
			return "application"
		case "application/x-ms-shortcut":
			return "lnk"
		case "application/x-ms-wmd":
			return "wmd"
		case "application/x-ms-wmz":
			return "wmz"
		case "application/x-ms-xbap":
			return "xbap"
		case "application/x-msaccess":
			return "mdb"
		case "application/x-msbinder":
			return "obd"
		case "application/x-mscardfile":
			return "crd"
		case "application/x-msclip":
			return "clp"
		case "application/x-msdownload":
			return "exe"
		case "application/x-msmediaview":
			return "mvb"
		case "application/x-msmetafile":
			return "wmf"
		case "application/x-msmoney":
			return "mny"
		case "application/x-mspublisher":
			return "pub"
		case "application/x-msschedule":
			return "scd"
		case "application/x-msterminal":
			return "trm"
		case "application/x-mswrite":
			return "wri"
		case "application/x-netcdf":
			return "nc"
		case "application/x-nzb":
			return "nzb"
		case "application/x-pkcs12":
			return "p12"
		case "application/x-pkcs7-certificates":
			return "p7b"
		case "application/x-pkcs7-certreqresp":
			return "p7r"
		case "application/x-rar-compressed":
			return "rar"
		case "application/x-research-info-systems":
			return "ris"
		case "application/x-sh":
			return "sh"
		case "application/x-shar":
			return "shar"
		case "application/x-shockwave-flash":
			return "swf"
		case "application/x-silverlight-app":
			return "xap"
		case "application/x-sql":
			return "sql"
		case "application/x-stuffit":
			return "sit"
		case "application/x-stuffitx":
			return "sitx"
		case "application/x-subrip":
			return "srt"
		case "application/x-sv4cpio":
			return "sv4cpio"
		case "application/x-sv4crc":
			return "sv4crc"
		case "application/x-t3vm-image":
			return "t3"
		case "application/x-tads":
			return "gam"
		case "application/x-tar":
			return "tar"
		case "application/x-tcl":
			return "tcl"
		case "application/x-tex":
			return "tex"
		case "application/x-tex-tfm":
			return "tfm"
		case "application/x-texinfo":
			return "texinfo"
		case "application/x-tgif":
			return "obj"
		case "application/x-ustar":
			return "ustar"
		case "application/x-wais-source":
			return "src"
		case "application/x-x509-ca-cert":
			return "der"
		case "application/x-xfig":
			return "fig"
		case "application/x-xliff+xml":
			return "xlf"
		case "application/x-xpinstall":
			return "xpi"
		case "application/x-xz":
			return "xz"
		case "application/x-zmachine":
			return "z1"
		case "application/xaml+xml":
			return "xaml"
		case "application/xcap-diff+xml":
			return "xdf"
		case "application/xenc+xml":
			return "xenc"
		case "application/xhtml+xml":
			return "xhtml"
		case "application/xml":
			return "xml"
		case "application/xml-dtd":
			return "dtd"
		case "application/xop+xml":
			return "xop"
		case "application/xproc+xml":
			return "xpl"
		case "application/xslt+xml":
			return "xslt"
		case "application/xspf+xml":
			return "xspf"
		case "application/xv+xml":
			return "mxml"
		case "application/yang":
			return "yang"
		case "application/yin+xml":
			return "yin"
		case "application/zip":
			return "zip"
		case "audio/adpcm":
			return "adp"
		case "audio/basic":
			return "au"
		case "audio/midi":
			return "mid"
		case "audio/mp4":
			return "m4a"
		case "audio/mpeg":
			return "mpga"
		case "audio/ogg":
			return "oga"
		case "audio/s3m":
			return "s3m"
		case "audio/silk":
			return "sil"
		case "audio/vnd.dece.audio":
			return "uva"
		case "audio/vnd.digital-winds":
			return "eol"
		case "audio/vnd.dra":
			return "dra"
		case "audio/vnd.dts":
			return "dts"
		case "audio/vnd.dts.hd":
			return "dtshd"
		case "audio/vnd.lucent.voice":
			return "lvp"
		case "audio/vnd.ms-playready.media.pya":
			return "pya"
		case "audio/vnd.nuera.ecelp4800":
			return "ecelp4800"
		case "audio/vnd.nuera.ecelp7470":
			return "ecelp7470"
		case "audio/vnd.nuera.ecelp9600":
			return "ecelp9600"
		case "audio/vnd.rip":
			return "rip"
		case "audio/webm":
			return "weba"
		case "audio/x-aac":
			return "aac"
		case "audio/x-aiff":
			return "aif"
		case "audio/x-caf":
			return "caf"
		case "audio/x-flac":
			return "flac"
		case "audio/x-matroska":
			return "mka"
		case "audio/x-mpegurl":
			return "m3u"
		case "audio/x-ms-wax":
			return "wax"
		case "audio/x-ms-wma":
			return "wma"
		case "audio/x-pn-realaudio":
			return "ram"
		case "audio/x-pn-realaudio-plugin":
			return "rmp"
		case "audio/x-wav":
			return "wav"
		case "audio/xm":
			return "xm"
		case "chemical/x-cdx":
			return "cdx"
		case "chemical/x-cif":
			return "cif"
		case "chemical/x-cmdf":
			return "cmdf"
		case "chemical/x-cml":
			return "cml"
		case "chemical/x-csml":
			return "csml"
		case "chemical/x-xyz":
			return "xyz"
		case "font/collection":
			return "ttc"
		case "font/otf":
			return "otf"
		case "font/ttf":
			return "ttf"
		case "font/woff":
			return "woff"
		case "font/woff2":
			return "woff2"
		case "image/bmp":
			return "bmp"
		case "image/cgm":
			return "cgm"
		case "image/g3fax":
			return "g3"
		case "image/gif":
			return "gif"
		case "image/ief":
			return "ief"
		case "image/jpeg":
			return "jpeg"
		case "image/ktx":
			return "ktx"
		case "image/png":
			return "png"
		case "image/prs.btif":
			return "btif"
		case "image/sgi":
			return "sgi"
		case "image/svg+xml":
			return "svg"
		case "image/tiff":
			return "tiff"
		case "image/vnd.adobe.photoshop":
			return "psd"
		case "image/vnd.dece.graphic":
			return "uvi"
		case "image/vnd.djvu":
			return "djvu"
		case "image/vnd.dvb.subtitle":
			return "sub"
		case "image/vnd.dwg":
			return "dwg"
		case "image/vnd.dxf":
			return "dxf"
		case "image/vnd.fastbidsheet":
			return "fbs"
		case "image/vnd.fpx":
			return "fpx"
		case "image/vnd.fst":
			return "fst"
		case "image/vnd.fujixerox.edmics-mmr":
			return "mmr"
		case "image/vnd.fujixerox.edmics-rlc":
			return "rlc"
		case "image/vnd.ms-modi":
			return "mdi"
		case "image/vnd.ms-photo":
			return "wdp"
		case "image/vnd.net-fpx":
			return "npx"
		case "image/vnd.wap.wbmp":
			return "wbmp"
		case "image/vnd.xiff":
			return "xif"
		case "image/webp":
			return "webp"
		case "image/x-3ds":
			return "3ds"
		case "image/x-cmu-raster":
			return "ras"
		case "image/x-cmx":
			return "cmx"
		case "image/x-freehand":
			return "fh"
		case "image/x-icon":
			return "ico"
		case "image/x-mrsid-image":
			return "sid"
		case "image/x-pcx":
			return "pcx"
		case "image/x-pict":
			return "pic"
		case "image/x-portable-anymap":
			return "pnm"
		case "image/x-portable-bitmap":
			return "pbm"
		case "image/x-portable-graymap":
			return "pgm"
		case "image/x-portable-pixmap":
			return "ppm"
		case "image/x-rgb":
			return "rgb"
		case "image/x-tga":
			return "tga"
		case "image/x-xbitmap":
			return "xbm"
		case "image/x-xpixmap":
			return "xpm"
		case "image/x-xwindowdump":
			return "xwd"
		case "message/rfc822":
			return "eml"
		case "model/iges":
			return "igs"
		case "model/mesh":
			return "msh"
		case "model/vnd.collada+xml":
			return "dae"
		case "model/vnd.dwf":
			return "dwf"
		case "model/vnd.gdl":
			return "gdl"
		case "model/vnd.gtw":
			return "gtw"
		case "model/vnd.mts":
			return "mts"
		case "model/vnd.vtu":
			return "vtu"
		case "model/vrml":
			return "wrl"
		case "model/x3d+binary":
			return "x3db"
		case "model/x3d+vrml":
			return "x3dv"
		case "model/x3d+xml":
			return "x3d"
		case "text/cache-manifest":
			return "appcache"
		case "text/calendar":
			return "ics"
		case "text/css":
			return "css"
		case "text/csv":
			return "csv"
		case "text/html":
			return "html"
		case "text/n3":
			return "n3"
		case "text/plain":
			return "txt"
		case "text/prs.lines.tag":
			return "dsc"
		case "text/richtext":
			return "rtx"
		case "text/sgml":
			return "sgml"
		case "text/tab-separated-values":
			return "tsv"
		case "text/troff":
			return "t"
		case "text/turtle":
			return "ttl"
		case "text/uri-list":
			return "uri"
		case "text/vcard":
			return "vcard"
		case "text/vnd.curl":
			return "curl"
		case "text/vnd.curl.dcurl":
			return "dcurl"
		case "text/vnd.curl.mcurl":
			return "mcurl"
		case "text/vnd.curl.scurl":
			return "scurl"
		case "text/vnd.fly":
			return "fly"
		case "text/vnd.fmi.flexstor":
			return "flx"
		case "text/vnd.graphviz":
			return "gv"
		case "text/vnd.in3d.3dml":
			return "3dml"
		case "text/vnd.in3d.spot":
			return "spot"
		case "text/vnd.sun.j2me.app-descriptor":
			return "jad"
		case "text/vnd.wap.wml":
			return "wml"
		case "text/vnd.wap.wmlscript":
			return "wmls"
		case "text/x-asm":
			return "s"
		case "text/x-c":
			return "c"
		case "text/x-fortran":
			return "f"
		case "text/x-java-source":
			return "java"
		case "text/x-nfo":
			return "nfo"
		case "text/x-opml":
			return "opml"
		case "text/x-pascal":
			return "p"
		case "text/x-setext":
			return "etx"
		case "text/x-sfv":
			return "sfv"
		case "text/x-uuencode":
			return "uu"
		case "text/x-vcalendar":
			return "vcs"
		case "text/x-vcard":
			return "vcf"
		case "video/3gpp":
			return "3gp"
		case "video/3gpp2":
			return "3g2"
		case "video/h261":
			return "h261"
		case "video/h263":
			return "h263"
		case "video/h264":
			return "h264"
		case "video/jpeg":
			return "jpgv"
		case "video/jpm":
			return "jpm"
		case "video/mj2":
			return "mj2"
		case "video/mp4":
			return "mp4"
		case "video/mpeg":
			return "mpeg"
		case "video/ogg":
			return "ogv"
		case "video/quicktime":
			return "qt"
		case "video/vnd.dece.hd":
			return "uvh"
		case "video/vnd.dece.mobile":
			return "uvm"
		case "video/vnd.dece.pd":
			return "uvp"
		case "video/vnd.dece.sd":
			return "uvs"
		case "video/vnd.dece.video":
			return "uvv"
		case "video/vnd.dvb.file":
			return "dvb"
		case "video/vnd.fvt":
			return "fvt"
		case "video/vnd.mpegurl":
			return "mxu"
		case "video/vnd.ms-playready.media.pyv":
			return "pyv"
		case "video/vnd.uvvu.mp4":
			return "uvu"
		case "video/vnd.vivo":
			return "viv"
		case "video/webm":
			return "webm"
		case "video/x-f4v":
			return "f4v"
		case "video/x-fli":
			return "fli"
		case "video/x-flv":
			return "flv"
		case "video/x-m4v":
			return "m4v"
		case "video/x-matroska":
			return "mkv"
		case "video/x-mng":
			return "mng"
		case "video/x-ms-asf":
			return "asf"
		case "video/x-ms-vob":
			return "vob"
		case "video/x-ms-wm":
			return "wm"
		case "video/x-ms-wmv":
			return "wmv"
		case "video/x-ms-wmx":
			return "wmx"
		case "video/x-ms-wvx":
			return "wvx"
		case "video/x-msvideo":
			return "avi"
		case "video/x-sgi-movie":
			return "movie"
		case "video/x-smv":
			return "smv"
		case "x-conference/x-cooltalk":
			return "ice"
		default:
			return nil
		}
	}

}
