//
//  Mime.swift
//  MimeLibGenerator
//
//  Created by Ondrej Rafaj on 14/12/2016.
//  Copyright © 2016 manGoweb UK Ltd. All rights reserved.
//

import Foundation


// Warning: Following has been automaically generated!

public class Mime {
    
    public static func get(fileExtension ext: String) -> MimeType? {
        switch ext {
        case "ez":
            return .ez
        case "aw":
            return .aw
        case "atom":
            return .atom
        case "atomcat":
            return .atomcat
        case "atomsvc":
            return .atomsvc
        case "ccxml":
            return .ccxml
        case "cdmia":
            return .cdmia
        case "cdmic":
            return .cdmic
        case "cdmid":
            return .cdmid
        case "cdmio":
            return .cdmio
        case "cdmiq":
            return .cdmiq
        case "cu":
            return .cu
        case "davmount":
            return .davmount
        case "dbk":
            return .dbk
        case "dssc":
            return .dssc
        case "xdssc":
            return .xdssc
        case "ecma":
            return .ecma
        case "emma":
            return .emma
        case "epub":
            return .epub
        case "exi":
            return .exi
        case "pfr":
            return .pfr
        case "woff":
            return .woff
        case "gml":
            return .gml
        case "gpx":
            return .gpx
        case "gxf":
            return .gxf
        case "stk":
            return .stk
        case "ink":
            return .ink
        case "ipfix":
            return .ipfix
        case "jar":
            return .jar
        case "ser":
            return .ser
        case "class":
            return ._class
        case "js":
            return .js
        case "json":
            return .json
        case "jsonml":
            return .jsonml
        case "lostxml":
            return .lostxml
        case "hqx":
            return .hqx
        case "cpt":
            return .cpt
        case "mads":
            return .mads
        case "mrc":
            return .mrc
        case "mrcx":
            return .mrcx
        case "ma":
            return .ma
        case "mathml":
            return .mathml
        case "mbox":
            return .mbox
        case "mscml":
            return .mscml
        case "metalink":
            return .metalink
        case "meta4":
            return .meta4
        case "mets":
            return .mets
        case "mods":
            return .mods
        case "m21":
            return .m21
        case "mp4s":
            return .mp4s
        case "doc":
            return .doc
        case "mxf":
            return .mxf
        case "bin":
            return .bin
        case "oda":
            return .oda
        case "opf":
            return .opf
        case "ogx":
            return .ogx
        case "omdoc":
            return .omdoc
        case "onetoc":
            return .onetoc
        case "oxps":
            return .oxps
        case "xer":
            return .xer
        case "pdf":
            return .pdf
        case "pgp":
            return .pgp
        case "asc":
            return .asc
        case "prf":
            return .prf
        case "p10":
            return .p10
        case "p7m":
            return .p7m
        case "p7s":
            return .p7s
        case "p8":
            return .p8
        case "ac":
            return .ac
        case "cer":
            return .cer
        case "crl":
            return .crl
        case "pkipath":
            return .pkipath
        case "pki":
            return .pki
        case "pls":
            return .pls
        case "ai":
            return .ai
        case "cww":
            return .cww
        case "pskcxml":
            return .pskcxml
        case "rdf":
            return .rdf
        case "rif":
            return .rif
        case "rnc":
            return .rnc
        case "rl":
            return .rl
        case "rld":
            return .rld
        case "rs":
            return .rs
        case "gbr":
            return .gbr
        case "mft":
            return .mft
        case "roa":
            return .roa
        case "rsd":
            return .rsd
        case "rss":
            return .rss
        case "rtf":
            return .rtf
        case "sbml":
            return .sbml
        case "scq":
            return .scq
        case "scs":
            return .scs
        case "spq":
            return .spq
        case "spp":
            return .spp
        case "sdp":
            return .sdp
        case "setpay":
            return .setpay
        case "setreg":
            return .setreg
        case "shf":
            return .shf
        case "smi":
            return .smi
        case "rq":
            return .rq
        case "srx":
            return .srx
        case "gram":
            return .gram
        case "grxml":
            return .grxml
        case "sru":
            return .sru
        case "ssdl":
            return .ssdl
        case "ssml":
            return .ssml
        case "tei":
            return .tei
        case "tfi":
            return .tfi
        case "tsd":
            return .tsd
        case "plb":
            return .plb
        case "psb":
            return .psb
        case "pvb":
            return .pvb
        case "tcap":
            return .tcap
        case "pwn":
            return .pwn
        case "aso":
            return .aso
        case "imp":
            return .imp
        case "acu":
            return .acu
        case "atc":
            return .atc
        case "air":
            return .air
        case "fcdt":
            return .fcdt
        case "fxp":
            return .fxp
        case "xdp":
            return .xdp
        case "xfdf":
            return .xfdf
        case "ahead":
            return .ahead
        case "azf":
            return .azf
        case "azs":
            return .azs
        case "azw":
            return .azw
        case "acc":
            return .acc
        case "ami":
            return .ami
        case "apk":
            return .apk
        case "cii":
            return .cii
        case "fti":
            return .fti
        case "atx":
            return .atx
        case "mpkg":
            return .mpkg
        case "m3u8":
            return .m3u8
        case "swi":
            return .swi
        case "iota":
            return .iota
        case "aep":
            return .aep
        case "mpm":
            return .mpm
        case "bmi":
            return .bmi
        case "rep":
            return .rep
        case "cdxml":
            return .cdxml
        case "mmd":
            return .mmd
        case "cdy":
            return .cdy
        case "cla":
            return .cla
        case "rp9":
            return .rp9
        case "c4g":
            return .c4g
        case "c11amc":
            return .c11amc
        case "c11amz":
            return .c11amz
        case "csp":
            return .csp
        case "cdbcmsg":
            return .cdbcmsg
        case "cmc":
            return .cmc
        case "clkx":
            return .clkx
        case "clkk":
            return .clkk
        case "clkp":
            return .clkp
        case "clkt":
            return .clkt
        case "clkw":
            return .clkw
        case "wbs":
            return .wbs
        case "pml":
            return .pml
        case "ppd":
            return .ppd
        case "car":
            return .car
        case "pcurl":
            return .pcurl
        case "dart":
            return .dart
        case "rdz":
            return .rdz
        case "uvf":
            return .uvf
        case "uvt":
            return .uvt
        case "uvx":
            return .uvx
        case "uvz":
            return .uvz
        case "fe_launch":
            return .fe_launch
        case "dna":
            return .dna
        case "mlp":
            return .mlp
        case "dpg":
            return .dpg
        case "dfac":
            return .dfac
        case "kpxx":
            return .kpxx
        case "ait":
            return .ait
        case "svc":
            return .svc
        case "geo":
            return .geo
        case "mag":
            return .mag
        case "nml":
            return .nml
        case "esf":
            return .esf
        case "msf":
            return .msf
        case "qam":
            return .qam
        case "slt":
            return .slt
        case "ssf":
            return .ssf
        case "es3":
            return .es3
        case "ez2":
            return .ez2
        case "ez3":
            return .ez3
        case "fdf":
            return .fdf
        case "mseed":
            return .mseed
        case "seed":
            return .seed
        case "gph":
            return .gph
        case "ftc":
            return .ftc
        case "fm":
            return .fm
        case "fnc":
            return .fnc
        case "ltf":
            return .ltf
        case "fsc":
            return .fsc
        case "oas":
            return .oas
        case "oa2":
            return .oa2
        case "oa3":
            return .oa3
        case "fg5":
            return .fg5
        case "bh2":
            return .bh2
        case "ddd":
            return .ddd
        case "xdw":
            return .xdw
        case "xbd":
            return .xbd
        case "fzs":
            return .fzs
        case "txd":
            return .txd
        case "ggb":
            return .ggb
        case "ggt":
            return .ggt
        case "gex":
            return .gex
        case "gxt":
            return .gxt
        case "g2w":
            return .g2w
        case "g3w":
            return .g3w
        case "gmx":
            return .gmx
        case "kml":
            return .kml
        case "kmz":
            return .kmz
        case "gqf":
            return .gqf
        case "gac":
            return .gac
        case "ghf":
            return .ghf
        case "gim":
            return .gim
        case "grv":
            return .grv
        case "gtm":
            return .gtm
        case "tpl":
            return .tpl
        case "vcg":
            return .vcg
        case "hal":
            return .hal
        case "zmm":
            return .zmm
        case "hbci":
            return .hbci
        case "les":
            return .les
        case "hpgl":
            return .hpgl
        case "hpid":
            return .hpid
        case "hps":
            return .hps
        case "jlt":
            return .jlt
        case "pcl":
            return .pcl
        case "pclxl":
            return .pclxl
        case "sfd-hdstx":
            return .sfdHdstx
        case "mpy":
            return .mpy
        case "afp":
            return .afp
        case "irm":
            return .irm
        case "sc":
            return .sc
        case "icc":
            return .icc
        case "igl":
            return .igl
        case "ivp":
            return .ivp
        case "ivu":
            return .ivu
        case "igm":
            return .igm
        case "xpw":
            return .xpw
        case "i2g":
            return .i2g
        case "qbo":
            return .qbo
        case "qfx":
            return .qfx
        case "rcprofile":
            return .rcprofile
        case "irp":
            return .irp
        case "xpr":
            return .xpr
        case "fcs":
            return .fcs
        case "jam":
            return .jam
        case "rms":
            return .rms
        case "jisp":
            return .jisp
        case "joda":
            return .joda
        case "ktz":
            return .ktz
        case "karbon":
            return .karbon
        case "chrt":
            return .chrt
        case "kfo":
            return .kfo
        case "flw":
            return .flw
        case "kon":
            return .kon
        case "kpr":
            return .kpr
        case "ksp":
            return .ksp
        case "kwd":
            return .kwd
        case "htke":
            return .htke
        case "kia":
            return .kia
        case "kne":
            return .kne
        case "skp":
            return .skp
        case "sse":
            return .sse
        case "lasxml":
            return .lasxml
        case "lbd":
            return .lbd
        case "lbe":
            return .lbe
        case "123":
            return ._123
        case "apr":
            return .apr
        case "pre":
            return .pre
        case "nsf":
            return .nsf
        case "org":
            return .org
        case "scm":
            return .scm
        case "lwp":
            return .lwp
        case "portpkg":
            return .portpkg
        case "mcd":
            return .mcd
        case "mc1":
            return .mc1
        case "cdkey":
            return .cdkey
        case "mwf":
            return .mwf
        case "mfm":
            return .mfm
        case "flo":
            return .flo
        case "igx":
            return .igx
        case "mif":
            return .mif
        case "daf":
            return .daf
        case "dis":
            return .dis
        case "mbk":
            return .mbk
        case "mqy":
            return .mqy
        case "msl":
            return .msl
        case "plc":
            return .plc
        case "txf":
            return .txf
        case "mpn":
            return .mpn
        case "mpc":
            return .mpc
        case "xul":
            return .xul
        case "cil":
            return .cil
        case "cab":
            return .cab
        case "xls":
            return .xls
        case "xlam":
            return .xlam
        case "xlsb":
            return .xlsb
        case "xlsm":
            return .xlsm
        case "xltm":
            return .xltm
        case "eot":
            return .eot
        case "chm":
            return .chm
        case "ims":
            return .ims
        case "lrm":
            return .lrm
        case "thmx":
            return .thmx
        case "cat":
            return .cat
        case "stl":
            return .stl
        case "ppt":
            return .ppt
        case "ppam":
            return .ppam
        case "pptm":
            return .pptm
        case "sldm":
            return .sldm
        case "ppsm":
            return .ppsm
        case "potm":
            return .potm
        case "mpp":
            return .mpp
        case "docm":
            return .docm
        case "dotm":
            return .dotm
        case "wps":
            return .wps
        case "wpl":
            return .wpl
        case "xps":
            return .xps
        case "mseq":
            return .mseq
        case "mus":
            return .mus
        case "msty":
            return .msty
        case "taglet":
            return .taglet
        case "nlu":
            return .nlu
        case "ntf":
            return .ntf
        case "nnd":
            return .nnd
        case "nns":
            return .nns
        case "nnw":
            return .nnw
        case "ngdat":
            return .ngdat
        case "n-gage":
            return .nGage
        case "rpst":
            return .rpst
        case "rpss":
            return .rpss
        case "edm":
            return .edm
        case "edx":
            return .edx
        case "ext":
            return .ext
        case "odc":
            return .odc
        case "otc":
            return .otc
        case "odb":
            return .odb
        case "odf":
            return .odf
        case "odft":
            return .odft
        case "odg":
            return .odg
        case "otg":
            return .otg
        case "odi":
            return .odi
        case "oti":
            return .oti
        case "odp":
            return .odp
        case "otp":
            return .otp
        case "ods":
            return .ods
        case "ots":
            return .ots
        case "odt":
            return .odt
        case "odm":
            return .odm
        case "ott":
            return .ott
        case "oth":
            return .oth
        case "xo":
            return .xo
        case "dd2":
            return .dd2
        case "oxt":
            return .oxt
        case "pptx":
            return .pptx
        case "sldx":
            return .sldx
        case "ppsx":
            return .ppsx
        case "potx":
            return .potx
        case "xlsx":
            return .xlsx
        case "xltx":
            return .xltx
        case "docx":
            return .docx
        case "dotx":
            return .dotx
        case "mgp":
            return .mgp
        case "dp":
            return .dp
        case "esa":
            return .esa
        case "pdb":
            return .pdb
        case "paw":
            return .paw
        case "str":
            return .str
        case "ei6":
            return .ei6
        case "efif":
            return .efif
        case "wg":
            return .wg
        case "plf":
            return .plf
        case "pbd":
            return .pbd
        case "box":
            return .box
        case "mgz":
            return .mgz
        case "qps":
            return .qps
        case "ptid":
            return .ptid
        case "qxd":
            return .qxd
        case "bed":
            return .bed
        case "mxl":
            return .mxl
        case "musicxml":
            return .musicxml
        case "cryptonote":
            return .cryptonote
        case "cod":
            return .cod
        case "rm":
            return .rm
        case "rmvb":
            return .rmvb
        case "link66":
            return .link66
        case "st":
            return .st
        case "see":
            return .see
        case "sema":
            return .sema
        case "semd":
            return .semd
        case "semf":
            return .semf
        case "ifm":
            return .ifm
        case "itp":
            return .itp
        case "iif":
            return .iif
        case "ipk":
            return .ipk
        case "twd":
            return .twd
        case "mmf":
            return .mmf
        case "teacher":
            return .teacher
        case "sdkm":
            return .sdkm
        case "dxp":
            return .dxp
        case "sfs":
            return .sfs
        case "sdc":
            return .sdc
        case "sda":
            return .sda
        case "sdd":
            return .sdd
        case "smf":
            return .smf
        case "sdw":
            return .sdw
        case "sgl":
            return .sgl
        case "smzip":
            return .smzip
        case "sm":
            return .sm
        case "sxc":
            return .sxc
        case "stc":
            return .stc
        case "sxd":
            return .sxd
        case "std":
            return .std
        case "sxi":
            return .sxi
        case "sti":
            return .sti
        case "sxm":
            return .sxm
        case "sxw":
            return .sxw
        case "sxg":
            return .sxg
        case "stw":
            return .stw
        case "sus":
            return .sus
        case "svd":
            return .svd
        case "sis":
            return .sis
        case "xsm":
            return .xsm
        case "bdm":
            return .bdm
        case "xdm":
            return .xdm
        case "tao":
            return .tao
        case "pcap":
            return .pcap
        case "tmo":
            return .tmo
        case "tpt":
            return .tpt
        case "mxs":
            return .mxs
        case "tra":
            return .tra
        case "ufd":
            return .ufd
        case "utz":
            return .utz
        case "umj":
            return .umj
        case "unityweb":
            return .unityweb
        case "uoml":
            return .uoml
        case "vcx":
            return .vcx
        case "vsd":
            return .vsd
        case "vis":
            return .vis
        case "vsf":
            return .vsf
        case "wbxml":
            return .wbxml
        case "wmlc":
            return .wmlc
        case "wmlsc":
            return .wmlsc
        case "wtb":
            return .wtb
        case "nbp":
            return .nbp
        case "wpd":
            return .wpd
        case "wqd":
            return .wqd
        case "stf":
            return .stf
        case "xar":
            return .xar
        case "xfdl":
            return .xfdl
        case "hvd":
            return .hvd
        case "hvs":
            return .hvs
        case "hvp":
            return .hvp
        case "osf":
            return .osf
        case "osfpvg":
            return .osfpvg
        case "saf":
            return .saf
        case "spf":
            return .spf
        case "cmp":
            return .cmp
        case "zir":
            return .zir
        case "zaz":
            return .zaz
        case "vxml":
            return .vxml
        case "wgt":
            return .wgt
        case "hlp":
            return .hlp
        case "wsdl":
            return .wsdl
        case "wspolicy":
            return .wspolicy
        case "7z":
            return ._7z
        case "abw":
            return .abw
        case "ace":
            return .ace
        case "dmg":
            return .dmg
        case "aab":
            return .aab
        case "aam":
            return .aam
        case "aas":
            return .aas
        case "bcpio":
            return .bcpio
        case "torrent":
            return .torrent
        case "blb":
            return .blb
        case "bz":
            return .bz
        case "bz2":
            return .bz2
        case "cbr":
            return .cbr
        case "vcd":
            return .vcd
        case "cfs":
            return .cfs
        case "chat":
            return .chat
        case "pgn":
            return .pgn
        case "nsc":
            return .nsc
        case "cpio":
            return .cpio
        case "csh":
            return .csh
        case "deb":
            return .deb
        case "dgc":
            return .dgc
        case "dir":
            return .dir
        case "wad":
            return .wad
        case "ncx":
            return .ncx
        case "dtb":
            return .dtb
        case "res":
            return .res
        case "dvi":
            return .dvi
        case "evy":
            return .evy
        case "eva":
            return .eva
        case "bdf":
            return .bdf
        case "gsf":
            return .gsf
        case "psf":
            return .psf
        case "otf":
            return .otf
        case "pcf":
            return .pcf
        case "snf":
            return .snf
        case "ttf":
            return .ttf
        case "pfa":
            return .pfa
        case "arc":
            return .arc
        case "spl":
            return .spl
        case "gca":
            return .gca
        case "ulx":
            return .ulx
        case "gnumeric":
            return .gnumeric
        case "gramps":
            return .gramps
        case "gtar":
            return .gtar
        case "hdf":
            return .hdf
        case "install":
            return .install
        case "iso":
            return .iso
        case "jnlp":
            return .jnlp
        case "latex":
            return .latex
        case "lzh":
            return .lzh
        case "mie":
            return .mie
        case "prc":
            return .prc
        case "application":
            return .application
        case "lnk":
            return .lnk
        case "wmd":
            return .wmd
        case "wmz":
            return .wmz
        case "xbap":
            return .xbap
        case "mdb":
            return .mdb
        case "obd":
            return .obd
        case "crd":
            return .crd
        case "clp":
            return .clp
        case "exe":
            return .exe
        case "mvb":
            return .mvb
        case "wmf":
            return .wmf
        case "mny":
            return .mny
        case "pub":
            return .pub
        case "scd":
            return .scd
        case "trm":
            return .trm
        case "wri":
            return .wri
        case "nc":
            return .nc
        case "nzb":
            return .nzb
        case "p12":
            return .p12
        case "p7b":
            return .p7b
        case "p7r":
            return .p7r
        case "rar":
            return .rar
        case "ris":
            return .ris
        case "sh":
            return .sh
        case "shar":
            return .shar
        case "swf":
            return .swf
        case "xap":
            return .xap
        case "sql":
            return .sql
        case "sit":
            return .sit
        case "sitx":
            return .sitx
        case "srt":
            return .srt
        case "sv4cpio":
            return .sv4cpio
        case "sv4crc":
            return .sv4crc
        case "t3":
            return .t3
        case "gam":
            return .gam
        case "tar":
            return .tar
        case "tcl":
            return .tcl
        case "tex":
            return .tex
        case "tfm":
            return .tfm
        case "texinfo":
            return .texinfo
        case "obj":
            return .obj
        case "ustar":
            return .ustar
        case "src":
            return .src
        case "der":
            return .der
        case "fig":
            return .fig
        case "xlf":
            return .xlf
        case "xpi":
            return .xpi
        case "xz":
            return .xz
        case "z1":
            return .z1
        case "xaml":
            return .xaml
        case "xdf":
            return .xdf
        case "xenc":
            return .xenc
        case "xhtml":
            return .xhtml
        case "xml":
            return .xml
        case "dtd":
            return .dtd
        case "xop":
            return .xop
        case "xpl":
            return .xpl
        case "xslt":
            return .xslt
        case "xspf":
            return .xspf
        case "mxml":
            return .mxml
        case "yang":
            return .yang
        case "yin":
            return .yin
        case "zip":
            return .zip
        case "adp":
            return .adp
        case "au":
            return .au
        case "mid":
            return .mid
        case "m4a":
            return .m4a
        case "mpga":
            return .mpga
        case "oga":
            return .oga
        case "s3m":
            return .s3m
        case "sil":
            return .sil
        case "uva":
            return .uva
        case "eol":
            return .eol
        case "dra":
            return .dra
        case "dts":
            return .dts
        case "dtshd":
            return .dtshd
        case "lvp":
            return .lvp
        case "pya":
            return .pya
        case "ecelp4800":
            return .ecelp4800
        case "ecelp7470":
            return .ecelp7470
        case "ecelp9600":
            return .ecelp9600
        case "rip":
            return .rip
        case "weba":
            return .weba
        case "aac":
            return .aac
        case "aif":
            return .aif
        case "caf":
            return .caf
        case "flac":
            return .flac
        case "mka":
            return .mka
        case "m3u":
            return .m3u
        case "wax":
            return .wax
        case "wma":
            return .wma
        case "ram":
            return .ram
        case "rmp":
            return .rmp
        case "wav":
            return .wav
        case "xm":
            return .xm
        case "cdx":
            return .cdx
        case "cif":
            return .cif
        case "cmdf":
            return .cmdf
        case "cml":
            return .cml
        case "csml":
            return .csml
        case "xyz":
            return .xyz
        case "bmp":
            return .bmp
        case "cgm":
            return .cgm
        case "g3":
            return .g3
        case "gif":
            return .gif
        case "ief":
            return .ief
        case "jpeg":
            return .jpeg
        case "ktx":
            return .ktx
        case "png":
            return .png
        case "btif":
            return .btif
        case "sgi":
            return .sgi
        case "svg":
            return .svg
        case "tiff":
            return .tiff
        case "psd":
            return .psd
        case "uvi":
            return .uvi
        case "djvu":
            return .djvu
        case "sub":
            return .sub
        case "dwg":
            return .dwg
        case "dxf":
            return .dxf
        case "fbs":
            return .fbs
        case "fpx":
            return .fpx
        case "fst":
            return .fst
        case "mmr":
            return .mmr
        case "rlc":
            return .rlc
        case "mdi":
            return .mdi
        case "wdp":
            return .wdp
        case "npx":
            return .npx
        case "wbmp":
            return .wbmp
        case "xif":
            return .xif
        case "webp":
            return .webp
        case "3ds":
            return ._3ds
        case "ras":
            return .ras
        case "cmx":
            return .cmx
        case "fh":
            return .fh
        case "ico":
            return .ico
        case "sid":
            return .sid
        case "pcx":
            return .pcx
        case "pic":
            return .pic
        case "pnm":
            return .pnm
        case "pbm":
            return .pbm
        case "pgm":
            return .pgm
        case "ppm":
            return .ppm
        case "rgb":
            return .rgb
        case "tga":
            return .tga
        case "xbm":
            return .xbm
        case "xpm":
            return .xpm
        case "xwd":
            return .xwd
        case "eml":
            return .eml
        case "igs":
            return .igs
        case "msh":
            return .msh
        case "dae":
            return .dae
        case "dwf":
            return .dwf
        case "gdl":
            return .gdl
        case "gtw":
            return .gtw
        case "mts":
            return .mts
        case "vtu":
            return .vtu
        case "wrl":
            return .wrl
        case "x3db":
            return .x3db
        case "x3dv":
            return .x3dv
        case "x3d":
            return .x3d
        case "appcache":
            return .appcache
        case "ics":
            return .ics
        case "css":
            return .css
        case "csv":
            return .csv
        case "html":
            return .html
        case "n3":
            return .n3
        case "txt":
            return .txt
        case "dsc":
            return .dsc
        case "rtx":
            return .rtx
        case "sgml":
            return .sgml
        case "tsv":
            return .tsv
        case "t":
            return .t
        case "ttl":
            return .ttl
        case "uri":
            return .uri
        case "vcard":
            return .vcard
        case "curl":
            return .curl
        case "dcurl":
            return .dcurl
        case "mcurl":
            return .mcurl
        case "scurl":
            return .scurl
        case "sub":
            return .sub
        case "fly":
            return .fly
        case "flx":
            return .flx
        case "gv":
            return .gv
        case "3dml":
            return ._3dml
        case "spot":
            return .spot
        case "jad":
            return .jad
        case "wml":
            return .wml
        case "wmls":
            return .wmls
        case "s":
            return .s
        case "c":
            return .c
        case "f":
            return .f
        case "java":
            return .java
        case "nfo":
            return .nfo
        case "opml":
            return .opml
        case "p":
            return .p
        case "etx":
            return .etx
        case "sfv":
            return .sfv
        case "uu":
            return .uu
        case "vcs":
            return .vcs
        case "vcf":
            return .vcf
        case "3gp":
            return ._3gp
        case "3g2":
            return ._3g2
        case "h261":
            return .h261
        case "h263":
            return .h263
        case "h264":
            return .h264
        case "jpgv":
            return .jpgv
        case "jpm":
            return .jpm
        case "mj2":
            return .mj2
        case "mp4":
            return .mp4
        case "mpeg":
            return .mpeg
        case "ogv":
            return .ogv
        case "qt":
            return .qt
        case "uvh":
            return .uvh
        case "uvm":
            return .uvm
        case "uvp":
            return .uvp
        case "uvs":
            return .uvs
        case "uvv":
            return .uvv
        case "dvb":
            return .dvb
        case "fvt":
            return .fvt
        case "mxu":
            return .mxu
        case "pyv":
            return .pyv
        case "uvu":
            return .uvu
        case "viv":
            return .viv
        case "webm":
            return .webm
        case "f4v":
            return .f4v
        case "fli":
            return .fli
        case "flv":
            return .flv
        case "m4v":
            return .m4v
        case "mkv":
            return .mkv
        case "mng":
            return .mng
        case "asf":
            return .asf
        case "vob":
            return .vob
        case "wm":
            return .wm
        case "wmv":
            return .wmv
        case "wmx":
            return .wmx
        case "wvx":
            return .wvx
        case "avi":
            return .avi
        case "movie":
            return .movie
        case "smv":
            return .smv
        case "ice":
            return .ice
        default:
            return nil
        }
    }
    
}
